### PR TITLE
Changes to proxy compose settings to support LDAP Authorization.

### PR DESCRIPTION
**Pull request by lukwam**

### CODE REVIEW

**Comment by geoffjentry** [comment]
Wheel hath chosen @scottfrazer @mcovarr

**Comment by mcovarr** [comment]
Maybe the wheel should consider having a devops person review this?  I don't know what's going on in this file.

**Comment by lukwam** [comment]
I was asked to modify all the services so that the /api endpoint authorizes users based on their membership in ldap (filrecloud registration).

Those are the four new lines added to the end of the file.

The other changes are to remove things that are already set as the defaults in the openidc-proxy, so there is no reason to be specifying them. You only need to specify values that are different from the defaults.  

The defaults are visible here:

https://github.com/broadinstitute/openidc-baseimage/blob/master/run.sh

and here

https://github.com/broadinstitute/dockerfiles/blob/master/openidc-proxy/override.sh

I also noticed that cromwell and thurloe are the only ones that run on port 8000, rather than port 8080, so that is why you are having to specify the PROXY_URLs as they are non-standard.  All the other services in firecloud run on port 8080.

**Comment by geoffjentry** [comment]
@lukwam re the port, the people setting up the firecloud environments can twiddle the port to be whatever they want via the config. It's not hardwired into cromwell.

**Pull request merged**
