### PR TITLE
DO NOT MERGE - Persistence WIP

### PR DESCRIPTION
**Pull request by mcovarr**
DO NOT MERGE YET!

Hopefully a final-ish version of the DataAccess API to unblock its implementation in Slick.  

RIP StoreActor, SymbolStore, and ExecutionStore.  The spirit of ExecutionStore lives on in WorkflowActor, and maybe SymbolStore might find a place there too to rid us of some Await.result()s.  StoreActor is dead for real.  

Known issues:

FIXED ~~1) The Docker test is broken because the backend-specific initialization was accidentally refactored away.  Shouldn't be a big deal to restore that.~~
2) All other tests pass, but that might just be because the restart test stinks.  There are worrisome messages being emitted from that test which need to be tracked down and have assertions put on them.  It might also be a good idea to test restarting a workflow more complex than "Hello World".
3) No persistence of BackendInfo yet, shouldn't be tough but that needs a bit of discussion.
4) More Await.results() in WorkflowActor than I would like or are probably necessary.  This could be a separate Tech Debt issue. At least DataAccess is fully async.

### CODE REVIEW

**Comment by geoffjentry** [comment]
Does this completely supersede #56 - i.e. should that one be closed?

**Comment by mcovarr** [comment]
Hmm, not sure.  #56 is from persistence to develop, #64 is from mlc_persistence to persistence.

**Comment by geoffjentry** [comment]
But you shouldn't need the PR for that. Can't you make this PR be against `develop`?

**Comment by mcovarr** [comment]
Sure, if that's what we want.

**Pull request closed without merging**
