### PR TITLE
Add Intel to AUTHORS file

### PR DESCRIPTION
**Pull request by geoffjentry**
Adding an AUTHORS file with Broad and Intel present

### CODE REVIEW

**Comment by geoffjentry** [comment]
@scottfrazer @francares

**Comment by francares** [comment]
LGTM :+1:

**Comment by cjllanwarne** [comment]
Uh, if this is causing test failures, then we have something very wrong in our tests

**Comment by geoffjentry** [comment]
@cjllanwarne I'm going to go out on a limb and say that the test failure had nothing to do with this change. Just a guess.

**Comment by scottfrazer** [comment]
👍

**Pull request merged**
