### PR TITLE
S3 permissions errors using Cromwell 37+ BA-4740 (#4740)

### PR DESCRIPTION
**Pull request by AlekseiLitkovetc**
Add a pull request for the [BA-4740](https://broadworkbench.atlassian.net/browse/BA-4740) issue

### CODE REVIEW

**Comment by geoffjentry** [comment]
@alexagrf Would it be possible to add some tests here? I realize that it can be difficult to do that w/ auth code, so if this seems like a challenge perhaps we can work out a way w/ you to develop some integration tests we could fold into our internal system

**Comment by geoffjentry** [comment]
@AlekseiLitkovetc Also a heads up that all the files in the `lerch/s3fs` package Is a copy from a [library](https://github.com/elerch/Amazon-S3-FileSystem-NIO2) forked by @elerch and should also be folded in over there once complete.

**Comment by AlekseiLitkovetc** [comment]
> @AlekseiLitkovetc Also a heads up that all the files in the `lerch/s3fs` package Is a copy from a [library](https://github.com/elerch/Amazon-S3-FileSystem-NIO2) forked by @elerch and should also be folded in over there once complete.

@geoffjentry, thank you for your note!
Am I correct that we need to create a  pull request for the @elerch repository with corresponding changes at first?
If yes, I'll take care of it :)

**Comment by geoffjentry** [comment]
@AlekseiLitkovetc Usually what we've done is that once we merge a PR here which changes that library we make a PR in @elerch 's repo with the same changes. No need to do them simultaneously

**Comment by AlekseiLitkovetc** [comment]
@geoffjentry I've got it, thank you for your explanation.

**Pull request merged**
