### PR TITLE
Removed `/workflows/{version}/{id}/[logs/outputs]/{call}` endpoints. Closes #984

### LINKED ISSUE #984: REMOVE /workflows/{version}/{id}/[logs/outputs]/{call}
These endpoints are not being used by our major clients and represent a special case of data you can get from the metadata endpoint.  If a more efficient mechanism is needed to get this data in the future, we can add that as reshaping of the metadata output (e.g. .../metadata/{call})

Make it Gone, including from the README and Swagger!

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by geoffjentry** [comment]
👍

**Comment by mcovarr** [comment]
:+1:

**Comment by kshakir** [comment]
@mcovarr chosen as second reviewer. Please merge at will, or assign back with comments.

**Comment by mcovarr** [comment]
waiting on Travis

**Pull request merged**
