### PR TITLE
Added server side pagination for the workflow query using link headers.

### PR DESCRIPTION
**Pull request by jacarey**
This is modelled after github's pagination https://developer.github.com/v3/#pagination and Link Header RFC https://tools.ietf.org/html/rfc5988#section-5

### CODE REVIEW

**Comment by mcovarr** [comment]
README.md should be updated

**Comment by mcovarr** [comment]
Did you mean for this PR to be against develop?  We're currently using this branch for pluggable backend work which won't be usable for GOTC for quite a while.

**Comment by jacarey** [comment]
It was suggested that we create both a develop PR as well as for a hotfix. Had I been aware of the differences between the two branches I probably would not have created this PR... but we had already finished. Similar work will be done for a PR on the hotfix branch.

I'm happy to do whatever your team prefers. I suspect that this work will need to be duplicated in either case. :(

**Comment by mcovarr** [comment]
I'd be surprised if these changes can't be migrated fairly easily to 0.19-hotfix.  Metadata is an area under heavy construction on develop, and I suspect you're right this will need to be completely reimplemented once the dust settles.  😦 

I'd certainly thumbs up a 0.19-hotfix version of this with updates to the README.md.  😄

**Comment by jacarey** [comment]
Thanks Miguel. Sounds like it makes sense to close this PR. We'll create a hotfix PR with this functionality.

**Comment by mcovarr** [comment]
Actually now I'm realizing that the data retrieved by this API is not really of the "meta" variety, so it's possible this might continue to work in the PBE world as is.  You might want to leave this open, the worst that could happen is it gets disabled in a refactoring.

But PBE is probably a couple of months away, so if you'd like to use this functionality before then you'll still need to make a 0.19_hotfix version of this PR as well.

**Comment by jacarey** [comment]
Sounds good I'll leave this open for now and also create a new PR to add this functionaity to 0.19_hotfix

**Comment by jacarey** [comment]
This is the hotfix PR:
https://github.com/broadinstitute/cromwell/pull/842

**Comment by mcovarr** [comment]
@jacarey are the changes here consistent with what was merged to 0.19_hotfix?  If so I'd like to get this merged so it can be hooked up with the work I'm doing in #855.

**Comment by jacarey** [comment]
We made changes to avoid changing the model that was returned (opting for metadata instead) those changes aren't reflected here.

I will update this PR shortly.

**Comment by jacarey** [comment]
Ok I've updated the PR.

**Comment by mcovarr** [comment]
:+1:

**Comment by cjllanwarne** [comment]
Merge away! 👍

**Pull request merged**
