### PR TITLE
Move where the kamon stuff is started to fix a race condition

### PR DESCRIPTION
**Pull request by geoffjentry**
I'm curious if travis succeeds, but if it does this is intended to resolve our tyburn woes

### CODE REVIEW

**Comment by geoffjentry** [comment]
Ok - Travis succeeded. This *should* resolve the massive tyburn problems and it should now work about as well as it did previously

**Comment by mcovarr** [comment]
if that's the case then :+1: :+1: :+1:...

**Comment by cjllanwarne** [comment]
:+1:

**Comment by geoffjentry** [comment]
@mcovarr there's only one way to know for sure, but ...

**Pull request merged**
