### PR TITLE
Add sync command to force flush of disk writes

### PR DESCRIPTION
**Pull request by Horneth**
I know there is a more serious ticket for this issue, but it seems like a number of centaur local tests have been failing again lately due to `expected "hello" but got ""` kind of errors.
I found this https://linux.die.net/man/2/sync and have been restarting centaur local on this branch a few times and none of them have failed so far. I don't think it entirely fixes the issue though.

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by ruchim** [comment]
:+1: are we going to rip off the sleeps maybe?!

**Comment by Horneth** [comment]
@ruchim yes I think we could remove them it's been proven that they're useless (or too short -_-)

**Comment by delocalizer** [comment]
Depending on how much memory you've got, what else is happening on the box, and type of filesystem, `sync` can be a really expensive call... for example on one of our servers it typically takes about 10 seconds to return and uses 100% of 1 core in system cpu. When you run cromwell on that box and throw a thousand workflows at it, you end up with load like this:
```
top - 16:16:42 up 196 days,  6:34, 17 users,  load average: 806.48, 618.79, 413.58
Tasks: 4596 total, 829 running, 3766 sleeping,   1 stopped,   0 zombie
%Cpu(s):  1.4 us,  0.5 sy,  0.0 ni, 98.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 26386596+total, 15019235+free, 25326680 used, 88346944 buff/cache
KiB Swap: 67108860 total, 63149068 free,  3959792 used. 21917659+avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                       
 34965 cromwel+  20   0 42.622g 896064  20048 S   9.5  0.3   9:33.71 java                                          
 88343 cromwell  20   0  107892    360    284 R   7.3  0.0   0:28.21 sync                                          
 88838 cromwell  20   0  107892    360    284 R   7.3  0.0   0:27.78 sync                                          
 89911 cromwell  20   0  107892    360    284 R   7.3  0.0   0:23.89 sync                                          
 82582 cromwell  20   0  107892    356    284 R   6.7  0.0   0:31.86 sync                                          
 84039 cromwell  20   0  107892    356    284 R   6.7  0.0   0:32.20 sync                                          
 84917 cromwell  20   0  107892    360    284 R   6.7  0.0   0:28.46 sync                                          
 84962 cromwell  20   0  107892    356    284 R   6.7  0.0   0:28.67 sync                                          
 85475 cromwell  20   0  107892    356    284 R   6.7  0.0   0:28.88 sync                                          
 88464 cromwell  20   0  107892    356    284 R   6.7  0.0   0:28.14 sync                                          
 88465 cromwell  20   0  107892    360    284 R   6.7  0.0   0:27.49 sync                                          
 89112 cromwell  20   0  107892    356    284 R   6.7  0.0   0:27.73 sync                                          
 89398 cromwell  20   0  107892    360    284 R   6.7  0.0   0:22.13 sync                                          
 91615 cromwell  20   0  107892    356    284 R   6.7  0.0   0:12.59 sync                                          
 85206 cromwell  20   0  107892    356    284 R   6.1  0.0   0:27.26 sync                                          
 85628 cromwell  20   0  107892    356    284 R   6.1  0.0   0:28.59 sync                                          
 86528 cromwell  20   0  107892    360    284 R   6.1  0.0   0:27.53 sync                                          
 86833 cromwell  20   0  107892    360    284 R   6.1  0.0   0:27.62 sync                                          
 86848 cromwell  20   0  107892    356    284 R   6.1  0.0   0:28.30 sync                                          
 87034 cromwell  20   0  107892    356    284 R   6.1  0.0   0:27.50 sync                                          
 87256 cromwell  20   0  107892    360    284 R   6.1  0.0   0:27.27 sync                                          
 87465 cromwell  20   0  107892    360    284 R   6.1  0.0   0:28.04 sync                                          
 89692 cromwell  20   0  107892    360    284 R   6.1  0.0   0:22.21 sync                                          
 89976 cromwell  20   0  107892    356    284 R   6.1  0.0   0:23.04 sync                                          
 90467 cromwell  20   0  107892    356    284 R   6.1  0.0   0:19.82 sync                                          
 90988 cromwell  20   0  107892    360    284 R   6.1  0.0   0:13.32 sync                                          
 91427 cromwell  20   0  107892    356    284 R   6.1  0.0   0:13.01 sync                                          
 91645 cromwell  20   0  107892    356    284 R   6.1  0.0   0:12.66 sync                                          
 91971 cromwell  20   0  107892    360    284 R   6.1  0.0   0:11.03 sync                                          
 91973 cromwell  20   0  107892    360    284 R   6.1  0.0   0:10.64 sync                                          
 92276 cromwell  20   0  107892    356    284 R   6.1  0.0   0:09.48 sync                                          
 92612 cromwell  20   0  107892    356    284 R   6.1  0.0   0:08.25 sync                                          
 92756 cromwell  20   0  107892    356    284 R   6.1  0.0   0:08.03 sync                                          
 92834 cromwell  20   0  107892    356    284 R   6.1  0.0   0:07.79 sync                                          
 92959 cromwell  20   0  107892    356    284 R   6.1  0.0   0:07.61 sync 
...
```
which is not great

**Comment by delocalizer** [comment]
I'm going to try a build without that `sync`, and get some numbers to show load avg comparison

**Pull request merged**
