### PR TITLE
[Release process] Don't update Agora/Rawls and skip smoke tests

### PR DESCRIPTION
**Pull request by cjllanwarne**
### Wordy Description

* We will no longer update the womtool libraries in Agora and Rawls. We will accept the minor drift which may occur between "what Rawls thinks Cromwell could run" and "what Cromwell can actually run" until womtool as a service is adopted.
* We will no longer run smoke tests before and after each update. We will rely on swatomation and daily runs to detect problems.

### Current Process:
Current Process

### Proposed New Process:
Proposed New Process

### Proposed Hotfix Process:
Proposed Hotfix Process

### CODE REVIEW

**Comment by helgridly** [comment]
Uhhh. This makes me sad. The womtool work is on our board but I'm not sure when it'll be done. How prettily do I have to please for this to be held until it is? (I can try to get it prio bumped.)

**Comment by cjllanwarne** [comment]
@helgridly @davidangb for context, our understanding is that the absolute worst case here is, "Cromwell might make a change, meaning that Rawls/Agora won't validate something that Cromwell could run - if only it were to be submitted". Or alternatively, "Cromwell will regress and no longer succeed a workflow that Rawls thinks is fine".

Given the slow rate of change in the WDL draft-2 libraries recently, and the (very significant) pain in updating Rawls and Agora every release, that feels like a reasonable position for a few months while we await the switchover to womtool-as-a-service. Are we missing something?

**Comment by davidangb** [comment]
I'm really just trying to avoid "Cromwell will regress and no longer succeed a workflow that Rawls thinks is fine".  I think the process is reasonable as long as there are some safeguards against this, and if you tell me that the current test approach covers that, fine with me.

**Comment by cjllanwarne** [comment]
@davidangb I think that's fair. How about us saying that we'll continue to run the rawls/agora upgrades, but only if changes are made to the WDL draft 2 libraries. Otherwise we'll leave them at their current version?

In effect that probably means we won't be changing anything in the draft-2 libraries for the next few weeks... but it's good to have a fall back in case an urgent fix is needed (we didn't have anything planned in any case, which is why we didn't mind this freeze in the first place).

**Comment by salonishah11** [comment]
Do we want to keep this? (from Checklist for FC to accept Cromwell doc)
```
Run long-running submissions immediately before a dev deploy and observe that they pass after the new Cromwell version picks them up and completes them.
```
This was added after the Cromwell 34 release meltdown. There were some changes in it that caused all the running submissions to fail.

**Comment by cjllanwarne** [comment]
@salonishah11 I believe we now have upgrade tests in our CI which would catch that. @mcovarr @kshakir does that sound right?

**Pull request merged**
