### PR TITLE
[51 hotfix] Reduce blacklist cache metric spam [BA-6464]

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Comment by mcovarr** [comment]
hmm perhaps just take the workflow ID out so we can still identify hot spots?

**Comment by cjllanwarne** [comment]
Definitely the workflow ID is ballooning the metrics... do we need both the group and the call name? Would just one of those be sufficient?

**Comment by mcovarr** [comment]
Not sure, we can err on the side of safety and do just the group for now.

**Comment by mcovarr** [comment]
This is the hotfix edition, I didn't title it appropriately.

**Comment by cjllanwarne** [comment]
In that case, do we want a `develop` edition? 😄

**Pull request merged**
