### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by EvanTheB**

### CODE REVIEW

**Comment by geoffjentry** [comment]
@EvanTheB just to double check, you did this by autogenerating the docs, right? Thanks for the catch.

**Comment by EvanTheB** [comment]
Hi Geoff,
I do not have a java dev environment, and did not know that the docs were generated! I just grepped for the help string. Please feel free to modify this branch

**Comment by kshakir** [comment]
FYI there's a hidden watermark at the top of the file that one can use in PRs to tell if the RESTAPI.md was manually or automatically updated. Example: https://github.com/broadinstitute/cromwell/blame/31/docs/api/RESTAPI.md#L1-L8

Also if one doesn't have a dev environment locally they can still use any public sbt docker. It will take a while as it downloads ~the entire internet~ all of the un-cached cromwell dependencies, but something like this will work:

```shell
docker \
  run \
  --rm \
  -v $PWD:$PWD \
  -w $PWD \
  hseeberger/scala-sbt \
  sbt generateRestApiDocs
```

**Comment by geoffjentry** [comment]
Thanks @evantheb I’ll update woth the aigogenerated version

**Comment by geoffjentry** [comment]
Closing this in favor of #3573

**Pull request closed without merging**
