### PR TITLE
Remove KV test in ServiceRegistryActorSpec Closes #1039

### LINKED ISSUE #1039: Assess/Fix/Implement Ignored Tests in ServiceRegistryActorSpec
The goal here is to look at the tests in the spec, and determine
1. does the test assess something valuable
2. if no, delete it (with an explanation in the PR)
3. if yes, either fix it up so it passes, or reimplement... whatever is more expedient

### PR DESCRIPTION
**Pull request by Horneth**
This test was actually testing the KV service (which already has a test spec) through the ServiceRegistry.
The service registry should have its own tests to assert that the message flow / service lookup is working, but not to test all possible services it knows about. See https://github.com/broadinstitute/cromwell/issues/1047

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Are there any useful tests of the ServiceRegistry itself? Otherwise, might as well just delete the whole file

**Comment by cjllanwarne** [comment]
But, I agree with the concept of not testing KVP service in `ServiceRegistrySpec` 👍

**Comment by Horneth** [comment]
There aren't but there could be. But until then we might as well remove the file yes.

**Comment by mcovarr** [comment]
top-flight removing :+1:

**Pull request merged**
