### PR TITLE
Add the docker command to the Cromwell container

### PR DESCRIPTION
**Pull request by coreone**

### CODE REVIEW

**Comment by mcovarr** [comment]
@coreone could you describe what's going on in these changes?

**Comment by ruchim** [comment]
@coreone once we have a little bit of a description, I'd love to review this PR (short & sweet), and you can choose any one other person from the team.

**Comment by coreone** [comment]
@ruchim @mcovarr This is just to add the docker executable to the Cromwell container such that Cromwell can run local workflows using the docker command when Cromwell itself is running inside a container. The magic to make it all work is to mount the /var/run/docker.sock file into the Cromwell container so that the internal docker command can communicate with docker running on the host.

This is the PR to get around having to change code to use the docker API instead of shelling out to *docker* that we discussed in standup last week.

**Comment by mcovarr** [comment]
:+1:

**Comment by coreone** [comment]
Added some cleanup after the apt-get install to clean up that layer due to suggestions from @hjfbynara

**Comment by hjfbynara** [comment]
👍

**Comment by coreone** [comment]
@mcovarr do you want to re-approve after my changes, or are we going to say a cumulative 2 thumbs is good?  If good, I'll just merge.

**Comment by mcovarr** [comment]
:+1: even better

**Pull request merged**
