### PR TITLE
Randomize execution events index so they don't get overridden

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by kshakir** [comment]
I loathe coded non-determinism (ex: `Random` is ok when using a static seed), but I don't have a better solution off the top of my head. 👍

**Comment by Horneth** [comment]
The only other solution I can think of would be to query metadata to get the index but we don't want to do that :/

**Comment by mcovarr** [comment]
How does this play with the timing diagram?

**Comment by mcovarr** [comment]
:+1:

**Comment by Horneth** [comment]
@mcovarr timing diagram explicitly sorts the events by timestamp so this doesn't affect it.

**Pull request merged**
