### PR TITLE
Added DockerTest tag for HtCondor test

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1: spectagular

**Comment by francares** [comment]
I don't know the scope of DockerTest but this test the only thing it does is to check the docker command generated for the job. It does not execute anything.

**Comment by mcovarr** [comment]
@francares @cjllanwarne I think the actual issue here is that the "/tmp" assertions on lines 260 and 261 always fail on Mac, regardless of whether Docker is available or not.

**Comment by cjllanwarne** [comment]
@francares @mcovarr I've modified this (fairly bluntly however) so that it passes on mac. If you have a suggestion for a stronger test case let me know

**Comment by francares** [comment]
👍

**Pull request merged**
