### PR TITLE
Add a badge showing our license

### PR DESCRIPTION
**Pull request by geoffjentry**

### CODE REVIEW

**Comment by mcovarr** [comment]
Any way to round off the corners like our other badges?

screen shot 2016-02-19 at 11 30 15 am

**Comment by geoffjentry** [comment]
Indeed there is

**Comment by mcovarr** [comment]
Also yellow is kind of a "warny" color, maybe a happier green?  :frog:

**Comment by geoffjentry** [comment]
I was trying to pick something we haven't already used and we already have green.

The colors they have are here:
https://github.com/demhydraz/badge-collection/blob/master/licenses/bsd3clause.md

We could try to unify all of the colors but that might not be possible on some badges

**Comment by geoffjentry** [comment]
Although now I say it, obv travis & coveralls have dynamic colors based on status.

i liked the blue one originally anyways

**Comment by mcovarr** [comment]
Yeah that's a :gem:

**Comment by geoffjentry** [comment]
There ya go

**Comment by mcovarr** [comment]
:100: :+1:

**Comment by cjllanwarne** [comment]
:+1:

**Comment by pgrosu** [comment]
But where are the animations and flashing colors? :)

**Pull request merged**
