### PR TITLE
[BA-5888] Set Content Type for rc file to text/plain

### PR DESCRIPTION
**Pull request by pshapiro4broad**
- also remove unused object `ActionBuilder.Gsutil`

### CODE REVIEW

**Comment by dinvlad** [comment]
Would it be easy to set it for _all_ text outputs?

**Comment by pshapiro4broad** [comment]
> Would it be easy to set it for all text outputs? The other one I'm thinking about is monitoring.log

It's pretty much a per-file thing, so each file needs to be considered on its own. gsutil has some logic to infer file type from extension so a `.txt` file should have the correct content type already.

It does look like the monitoring file isn't text/plain and it would be easy to add. @mcovarr what do you think?

**Comment by mcovarr** [comment]
Actually I'd like to add a Centaur integration test for this, I can hopefully get this done today.

**Comment by pshapiro4broad** [comment]
> Actually I'd like to add a Centaur integration test for this, I can hopefully get this done today.

Thanks, I thought about doing this but wasn't sure how to do it.

**Pull request merged**
