### PR TITLE
changed globLinkCommand to use soft instead of hard links [BA-6089]

### PR DESCRIPTION
**Pull request by xiaofanjin**
I ran into the same issue as [#3876](https://github.com/broadinstitute/cromwell/issues/3876) running the chip-seq pipeline on beegfs, the workflow would stall looking for outputs after any individual task. I was able to resolve this by changing globLinkCommand to use soft instead of hard links, though not sure if soft links will cause problems in other contexts.

### CODE REVIEW

**Comment by xiaofanjin** [comment]
Ah ok, I'm not familiar with how to add configuration options. Depending on how involved a process it is / if there is some example from an earlier pull request I could follow, I would be happy to give it a shot. If not, I'm also ok with shelving this for now and just using an ad-hoc build in the meantime.

**Comment by cjllanwarne** [comment]
It shouldn't be too involved - there's an example of backend configuration being used in the same file you're updating [here](https://github.com/broadinstitute/cromwell/blob/develop/backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala#L132), which means it could be a per-backend option (see where the value could be set per-backend [here](https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/cromwell.examples.conf#L379)). Setting this value per-backend feels like the most correct way to do this to me.

Does that give you what you needed?

**Comment by xiaofanjin** [comment]
yes thanks!

**Comment by xiaofanjin** [comment]
seems like this was already implemented as a backend configuration option `glob-link-command`, so I simply updated the configuration example files to include an example of how to set `glob-link-command` to use soft-links instead. Was able to run on beeGFS with the updated configuration.

**Comment by cjllanwarne** [comment]
@xiaofanjin oh, that's great news - and thanks for feeding this discovery back into our examples docs!

**Pull request merged**
