### PR TITLE
Tagged integration tests as integration tests.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by kshakir** [comment]
@mcovarr as first reviewer. Travis already seems configured to ignore integration tests, so no other changes appeared necessary for this temporary fix.

**Comment by kshakir** [comment]
Oh, and `sbt assembly` already had _all_ of its tests disabled by build.sbt, so @geoffjentry's request that "when one checks out the code, sbt assembly not fail on an integration test" holds true without any other modifications. :wink:

**Comment by mcovarr** [comment]
True about `sbt assembly`, but do we want to run integration tests by default with `sbt test`?  Currently these are on by default and the `.travis.yml` is set up not to run them.

**Comment by kshakir** [comment]
Good point of discussion. I defaulted to "`sbt test` by default runs all tests, for now". Will leave it up to whomever you recommend as second reviewer to decide if integration tests should be excluded from `sbt test` as part of this PR.

**Comment by mcovarr** [comment]
Per the direction of the conversation on your integration testing doc, it sounds like there's a sentiment to disable integration (and maybe Docker) tests by default.  

The wheel has chosen @scottfrazer but I suspect @geoffjentry may have some opinions here as well. :smile:

**Comment by geoffjentry** [comment]
Note that I always just test via assembly because i'm too lazy to figure out the specific target I want so my opinionation might be lower than you suspect

**Comment by scottfrazer** [comment]
:+1:

**Comment by scottfrazer** [comment]
I think this is mergeable?

**Comment by kshakir** [comment]
Something happened to coveralls, but I don't think it was caused by this PR. In the meantime, @geoffjentry / @scottfrazer please review the latest commit (whenever you have time) while I check into it?

**Comment by geoffjentry** [comment]
:+1:

**Comment by scottfrazer** [comment]
:+1:

**Comment by mcovarr** [comment]
:+1:

**Comment by kshakir** [comment]
I was wrong. I did bust coveralls. Appears fixed with latest fixup. Ready to merge.

**Pull request merged**
