### PR TITLE
Allow declarations called 'version'

### LINKED ISSUE #3954: Allow 'version' as a variable name
See also https://github.com/openwdl/wdl/pull/239

### PR DESCRIPTION
**Pull request by cjllanwarne**
Closes #3954 
- [x] Cannot merge until https://github.com/openwdl/wdl/pull/240

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Note to reviewers: do *not* review the `WdlParser.java`s if you value your sanity. They're auto-generated parsers generated by hermes.

**Comment by aednichols** [comment]
Is this based on a grammar change in the openwdl repo?

**Comment by aednichols** [comment]
Aha, yep: https://github.com/openwdl/wdl/pull/240

**Comment by rsasch** [comment]
The `sbt` tests are reliably failing; any idea why?

**Comment by cjllanwarne** [comment]
@rsasch it was a test issue - they were asking for the lexer to tokenize WDL expressions like `3 + 3` in the "default" lexing mode. What went wrong was that I changed the "default" mode and moved almost all of its content into a new "main" mode.

So the fix was: make sure the lexer gets put into "main" mode before it tries to tokenize the expressions that we're testing for by first getting it to tokenize the "version 1.0" that starts a WDL document

**Comment by gemmalam** [comment]
@cjllanwarne it doesn't look like much activity has happen on the openwdl PR that blocks this PR. Is there anything left to do to get this moving?

**Pull request merged**
