### PR TITLE
Pulled wes2cromwell shim into Cromwell repo

### PR DESCRIPTION
**Pull request by geoffjentry**
**REVIEWERS: NB!!!!**  With a few minor exceptions in order to make our stricter compiler checks pass this was brought in as-is. **All** comments on the code shall be treated as ToL unless you're volunteering to clean it up yourself. However, feel free to seagull the SBT structure and such.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
ToL: it looks like there's a *lot* of overlap between this and the `cromwell.api.CromwellClient` classes (imported by Centaur, for example) - especially around the ADT definitions and the JSON tranforms - which would ideally be reconciled before either one is developed much further

**Comment by Horneth** [comment]
Re cromwell client: FWIW I really like the idea of having this code auto-generated from the swagger definition. Or even have another format than swagger if for whatever reason we don't want to generate it from that.

**Comment by geoffjentry** [comment]
@Horneth See #3860 - someone needs to fix our swagger :)

**Comment by geoffjentry** [comment]
Closing this - was pointed out to me that I shouldn't have copied `master` over

**Comment by geoffjentry** [comment]
Now with correct code

**Pull request merged**
