### PR TITLE
Revert workflow name embiggening, 0.22 style.

### PR DESCRIPTION
**Pull request by mcovarr**
Apparently there weren't any "real" workflow names > 100 chars, only one artificially long one created for test purposes, and Cloud SQL did not take kindly to the attempt to have a 500-char field as part of an index.  The test data was downsized and the embiggening commit reverted and the migration ran successfully.

### CODE REVIEW

**Comment by ruchim** [comment]
👍 👍 👍

**Comment by Horneth** [comment]
👍

**Comment by Horneth** [comment]
Should we create a ticket to gracefully handle workflow name > 100 char if that ever happens ?

**Comment by geoffjentry** [comment]
@Horneth #1725

**Pull request merged**
