### PR TITLE
Increase connection pool timeout for unit tests

### PR DESCRIPTION
**Pull request by mcovarr**
Makes the existing comment even more true.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
It really takes 30 seconds for unit tests to get a connection? 🤢

**Comment by mcovarr** [comment]
It really takes more than 3. 🙂

**Comment by mcovarr** [comment]
@geoffjentry yes, this is turning the knob higher and hoping for the best. The downstream tests succeeded except for the one that depended on cross-talking with the failed test...

**Comment by geoffjentry** [comment]
Discussed a bit w/ faces.

👍

**Pull request merged**
