### PR TITLE
Upgrade Akka to latest 2.3.x version

### PR DESCRIPTION
**Pull request by geoffjentry**
2.3.x is dead, long live 2.4.x. However I didn't want to progress to 2.4.x for a couple of reasons

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1: nice upgrading

**Comment by geoffjentry** [comment]
@mcovarr It is truly some of my finest work

**Comment by kshakir** [comment]
Tyranny be damned 👍

**Comment by geoffjentry** [comment]
"The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants."

**Pull request merged**
