### PR TITLE
Handle JsArray in CallCacheDiff [CROM-6600]

### PR DESCRIPTION
**Pull request by myazinn**
Closes https://broadworkbench.atlassian.net/browse/CROM-6600.
I also slightly change how `CallCacheDiffActor` handles JsObject keys. The old version can loose some values in rare case of field names collisions.

### CODE REVIEW

**Comment by aednichols** [comment]
Thanks for linking the issue, we will discuss these internally.

**Review by cjllanwarne — APPROVED** [review]
- [X] Tested with an `Array[File]` input
- [X] Tested with an `Array[Struct]` input which contains a file

This is great! Thanks @myazinn.

If you feel able, it'd be great to see a test case in https://github.com/broadinstitute/cromwell/blob/develop/engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCacheDiffActorSpec.scala to avoid regressions in the future, but even without one, I've tested this locally and it looks great to me. 👍

**Comment by myazinn** [comment]
Hi @cjllanwarne
Thanks for your review! I'll add new tests and notify you when I'm done.

**Review by mcovarr — APPROVED** [review]
Thank you for these fixes! 👍

**Pull request merged**
