### PR TITLE
The Great Escape

### LINKED ISSUE #4500: Can't escape quotes in WDL 1.0
Originally reported here:
https://gatkforums.broadinstitute.org/gatk/discussion/comment/54964#Comment_54964

Example workflow as the acceptance criteria:
```
version 1.0
workflow example{
    call print{
    }
}

task print{
    input{
        String s = "\""
    }
    command{
        echo "${s}"
    }
}
```

### PR DESCRIPTION
**Pull request by aednichols**
Closes #4500 

Requires https://github.com/openwdl/wdl/pull/303

My description over on OpenWDL:

>Right now, the grammar does not correctly handle strings like
>```
>String q1 = "leading text \" trailing text"
>```
>The example above is sliced up into one string `"leading text "` and three bare symbols `trailing`, `text`, `"` which is clearly wrong.
>
>This PR fixes the issue by preventing quotes that follow the escape character `\` from marking the end of a string.
>
>In regex terms, it adds a negative lookbehind for `\` inside the positive lookahead that stops at `"`.

### CODE REVIEW

**Comment by aednichols** [comment]
The requisite OpenWDL PR has merged

**Comment by aednichols** [comment]
@cjllanwarne regarding merges to master, there indeed was a merge of the grammar change for call blocks. The new parser worked just fine without the associated Cromwell changes, which is proof that the bugfix is safe with respect to WDL implementations.

**Comment by cjllanwarne** [comment]
It looks like by merging your other PR first, you may have come up against needing to rebase-in the new changes anyway?

**Comment by cjllanwarne** [comment]
Well either way, so long as after everything's done Cromwell is consistent with `OpenWDL/master`, I think we should be good

**Comment by aednichols** [comment]
A quick conflict resolve in IntellIJ took care of things very nicely. A sanity check is that the parser on this branch contains references both `$call_brace_block` and `(?<!\\\\)`

**Pull request merged**
