### PR TITLE
Store custom labels.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by ruchim** [comment]
:+1:

**Comment by cjllanwarne** [comment]
Wait... was this always this way? Can we centaur this at all (hmm, assuming a JES job request its own metadata)?

**Comment by cjllanwarne** [comment]
👍

**Comment by kshakir** [comment]
This is a small patch on the patch of #2067. Yes, labels and the sql converters both need better unit and or centaur tests.

**Pull request merged**
