### PR TITLE
Added the function 'defined' for optionals. Closes #1548

### LINKED ISSUE #1548: Implement new engine functions - (select first, select All, defined)
- [x] select_first
 - [x] select_all
 - [ ] defined

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

**Comment by geoffjentry** [comment]
@cjllanwarne If it wasn't already done, make sure to run this construct past our typical WDL focus panel folks. If this came direct from them, ignore me :)

**Comment by cjllanwarne** [comment]
@geoffjentry this was the last unfinished part of the optionals epic, and in the same ticket as `select_all` and `select_first`. I'm not sure why it wasn't done last time tbh... https://github.com/broadinstitute/cromwell/issues/1548

**Comment by geoffjentry** [comment]
@cjllanwarne Gotcha, thanks!

**Comment by mcovarr** [comment]
:+1:

**Pull request merged**
