### PR TITLE
Scala 2.12 and sbt updates

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Review by aednichols — APPROVED** [review]
💯

**Review by cjllanwarne — APPROVED** [review]
🎉

**Comment by cjllanwarne** [comment]
It looks like the recent scala-steward rush has caused a bunch of merge conflicts here, but this appears to resolve the sticky issues with `nowarn` in https://broadworkbench.atlassian.net/browse/CROM-6777

**Comment by kshakir** [comment]
Merge conflicts come with the territory of "not in sprint" weekend PRs 😅

RE: CROM-6777- As this PR mentions, the `nowarn` issues are a bug fixed by [scala/scala-collection-compat#426](https://dereferer.me/?https%3A//github.com/scala/scala-collection-compat/issues/426). But as of 2021-06-26 the fix [hasn't been released yet](https://github.com/scala/scala-collection-compat/releases). Whether the amelioration in this PR gets merged will depend on if upgrading scala/sbt appears on BT's priority backlog first, or if `@SethTisue` drops a new release of `scala-collection-compat` before then.

For now, in this branch the test command `sbt centaurCwlRunner/assembly` with `2.12.14` Works For Me™.

**Comment by cjllanwarne** [comment]
Will be much neater if a new release is published (see https://github.com/scala/scala-collection-compat/issues/466)

**Comment by kshakir** [comment]
Replaced by #6456

**Pull request closed without merging**
