### PR TITLE
Run cleanup explicitly since disabled tests no longer do it.  Closes #854

### LINKED ISSUE #854: What the f1, f2, f3?
These files now get left behind on test runs.

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Comment by mcovarr** [comment]
Removes files left over by tests.

**Comment by mcovarr** [comment]
@scottfrazer and @kshakir

**Comment by scottfrazer** [comment]
👍

**Comment by kshakir** [comment]
👍  merging

**Pull request merged**
