### PR TITLE
By executive order, turn on STRICT_ALL_TABLES.  Closes #539

### LINKED ISSUE #539: Turn on STRICT_ALL_TABLES in Travis

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Comment by Horneth** [comment]
:+1:

**Comment by kshakir** [comment]
:+1:

**Comment by kshakir** [comment]
See my comment over in #539

**Comment by mcovarr** [comment]
Closing this until the MySQL tests are restored

**Pull request merged**
