### PR TITLE
womtool and common

### PR DESCRIPTION
**Pull request by mcovarr**
`lenthall` has been posthumously executed and reinterred under `common`. The former `cromwell-womtool` artifact is now published as just `womtool`.

### CODE REVIEW

**Comment by Horneth** [comment]
I guess `lenthall` is now part of the `common` wealth

**Comment by mcovarr** [comment]
Centaur will need to be adjusted to reference the new name.

**Comment by cjllanwarne** [comment]
👍 I don't particularly like "common" since it's not at all clear what now goes in "common" vs "core" but 🤷‍♂️ I can't think of anything better

**Comment by mcovarr** [comment]
@cjllanwarne I agree with that and I think we should spell out what belongs where after everything is in one big happy repo.

**Pull request merged**
