### PR TITLE
Possibly removes some flakiness in sbt test

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by mcovarr** [comment]
Assuming the 0% coverage is an artifact of this class being loaded through reflection or something?

**Comment by Horneth** [comment]
@mcovarr hmm I guess technically this `NoopServiceActor` is 100% untested...
I'll move it to the test folder or test that it indeed does nothing

**Comment by cjllanwarne** [comment]
@Horneth I'm pretty sure this is one of the existing AkkaTestkit actors

**Comment by cjllanwarne** [comment]
(as in, a standard Akka thing, not one of our "roll our own"s

**Comment by mcovarr** [comment]
I can't imagine the standard TestKit actor responds to `cromwell.util.GracefulShutdownHelper.ShutdownCommand` though...

**Comment by Horneth** [comment]
The constructor signature needs to be exactly that since it's built reflectively, and like Miguel said it's better if it shuts itself down with the ShutdownCommand. Plus it's literally 5 lines so.. 😄

**Pull request merged**
