### PR TITLE
How do you spell that word anyway

### PR DESCRIPTION
**Pull request by scottfrazer**

### CODE REVIEW

**Comment by Horneth** [comment]
http://wheeldecide.com/?c1=preemptible&c2=preemptable

**Comment by geoffjentry** [comment]
This is the right way :+1:

**Comment by mcovarr** [comment]
[not clear](https://books.google.com/ngrams/graph?content=preemptible%2C+preemptable&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cpreemptible%3B%2Cc0%3B.t1%3B%2Cpreemptable%3B%2Cc0)

**Comment by mcovarr** [comment]
Hah, you perturbed (WOTD) the hash, the test needs to be updated

**Comment by geoffjentry** [comment]
Google actually says it the way Scott changed it to, that's what it should be

**Comment by mcovarr** [comment]
@geoffjentry actually Google says the 'a' variant is now ahead.  Personally I don't really care.  :stuck_out_tongue:

**Comment by Horneth** [comment]
http://www.oxforddictionaries.com/us/definition/american_english/pre-emptible?q=preemptible :heavy_check_mark: 
http://www.oxforddictionaries.com/us/spellcheck/american_english/?q=preemptable :heavy_multiplication_x:

**Comment by geoffjentry** [comment]
Not that I actually give a crap but discussed in person w/ @mcovarr but I meant that google cloud uses the 'i' variant for their actual product

**Comment by Horneth** [comment]
Yeah I just felt weird relying on Google Trends to decide how to spell a word -_-

**Comment by cjllanwarne** [comment]
@mcovarr You stopped the google graph too soon! [Up to date](https://books.google.com/ngrams/graph?content=preemptible%2Cpreemptable&year_start=1800&year_end=2015&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cpreemptible%3B%2Cc0%3B.t1%3B%2Cpreemptable%3B%2Cc0)

Etymology would suggest "-able" but "-ible" seems to be the way everyone else spells it now so my vote is for "-ible"

**Comment by cjllanwarne** [comment]
:+1:

**Comment by mcovarr** [comment]
:+1:

**Pull request merged**
