### PR TITLE
feat: Change WomFloat Double type implementation to BigDecimal [BA-5929]

### PR DESCRIPTION
**Pull request by SergeySdv**
Pull request for #BA-5929 issue:
https://broadworkbench.atlassian.net/browse/BA-5929

Changes:
Implemented  store larger values in WomFloat type via changing Double implementation to BigDecimal.
Also added validation logic of type compatibility.

### CODE REVIEW

**Comment by aednichols** [comment]
Is `BigDecimal` considered a fixed or a floating point number format? The [WDL spec](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md) definitely talks in terms of `Float`s so I'm not sure it's automatically an acceptable replacement.

**Comment by aednichols** [comment]
It's unlikely but I suppose possible that someone counts on the floating point behavior when it comes to loss of precision

**Comment by geoffjentry** [comment]
Those dropped bits are where I stick my steganographic messages to people

**Comment by aednichols** [comment]
Required xkcd

**Comment by SergeySdv** [comment]
> Is `BigDecimal` considered a fixed or a floating point number format? The [WDL spec](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md) definitely talks in terms of `Float`s so I'm not sure it's automatically an acceptable replacement.

Hello. Earlier @likeanowl made a PR with new WomType, and in previous discussion @cjllanwarne @geoffjentry suggested him to change existing type in cromwell backend. https://github.com/broadinstitute/cromwell/pull/5203#issuecomment-537206242

**Comment by aednichols** [comment]
Can you link to that discussion? The link you provided is to another comment in this PR, which may not be what you intended.

**Comment by likeanowl** [comment]
Hi @aednichols 
Since I've been mentioned, I guess that @SergeySdv wanted to refer to [this comment](https://github.com/broadinstitute/cromwell/pull/5135#issuecomment-525476031) in this [PR discussion](https://github.com/broadinstitute/cromwell/pull/5135)

**Comment by cjllanwarne** [comment]
So two things are happening here:
* We can't create a new WDL type but we can update the backend implementation in Cromwell to widen the supported values. My comment in the previous PR was making that case.
* We can only widen the supported values as far as the WDL spec allows.
  * As of WDL draft-2 and 1.0, the supported width is unspecified
  * As of WDL 2.0 it's defined thus: 
    * `Float` is a finite 64-bit IEEE-754 floating point number.
    * `Int` can be used to hold a signed Integer in the range `[-2^63, 2^63]`. 

So I think the best thing we could do is support the data types specified in WDL 2.0. Even though we'd be technically compliant with WDL 1.0 by going wider, I think it's just going to cause us headaches later.

I'd suggest starting by defining what we will and won't support by adding these test cases and trying to satisfy them:
* Support for the max value of a finite 64-bit IEEE-754 floating point number
* Disallowing the max value of a finite 64-bit IEEE-754 floating point number + 1
* Support for the min value of a finite 64-bit IEEE-754 floating point number
* Disallowing the min value of a finite 64-bit IEEE-754 floating point number - 1
* Support for the max value of a signed Integer in the range `[-2^63, 2^63]`
* Disallowing the max value of a signed Integer in the range `[-2^63, 2^63]` + 1
* Support for the min value of a signed Integer in the range `[-2^63, 2^63]`
* Disallowing the min value of a signed Integer in the range `[-2^63, 2^63]` - 1

By the way - I think if we do achieve this, there's a PR that's been sitting in the WDL spec for a while that could then merge as "implemented" so it'd be really cool to be able to achieve that!

**Comment by aednichols** [comment]
Hi @SergeySdv, we have marked your PR as "back with originator" so that you can update it based on the discussion. Once it is ready for review just leave a comment and we will take a look.

**Comment by cjllanwarne** [comment]
I'm going to close this PR for now (it seems like it's been pretty quiet since my last comment) - but if you want to reopen the PR at any time to re-start the conversation, please feel free.

**Pull request closed without merging**
