### PR TITLE
WX-1420 Fix GCP Batch label regex restriction

### PR DESCRIPTION
**Pull request by aednichols**
Clone of https://github.com/broadinstitute/cromwell/pull/7353 to run tests

### CODE REVIEW

**Review by jgainerdewar — APPROVED** [review]

**Comment by aednichols** [comment]
scalafmt

**Comment by bchen4** [comment]
> scalafmt

Fixed that by removing the test case. Now unit tests passed but the codecov failed.

**Comment by aednichols** [comment]
ah, nice

FWIW `scalafmt` is a keyword that when commented, runs the tool automatically

**Comment by aednichols** [comment]
Codecov isn't a mandatory check, we just don't have a way to tell Github to display the number without a red or green check.

**Comment by bchen4** [comment]
> Codecov isn't a mandatory check, we just don't have a way to tell Github to display the number without a red or green check.

Cool, so pending one more approval and then merge? (also finger cross on other tests)

**Comment by aednichols** [comment]
Since none of the functional code changed from https://github.com/broadinstitute/cromwell/pull/7353 which has two approvals, I will wait for tests to pass and admin-merge.

**Comment by aednichols** [comment]
Thanks for your contribution!

**Pull request merged**
