### PR TITLE
Report preempted calls as "Preempted" in metadata Closes #1207

### LINKED ISSUE #1207: Cromwell sets executionStatus to 'Failed' on preemption
Previously (cromwell 0.19 and before), Cromwell would set the executionStatus to 'Preempted' instead of `Failed`

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1:

**Comment by geoffjentry** [comment]
👍 

Does this need to be on hotfix as well? @jsotobroad @kcibul

**Comment by geoffjentry** [comment]
Actually I think @vivster7 was the person to tag from green

**Comment by vivster7** [comment]
Nope. Hot fix works as expected. This bug was found while testing .20

**Comment by geoffjentry** [comment]
Ah. Carry on then!

**Pull request merged**
