### PR TITLE
Renamed database schema to standardize naming. Closes #1423

### LINKED ISSUE #1423: Sync database scala with database sql
The `database.sql` artifact should follow the "convention over configuration" nature of [Rails](http://guides.rubyonrails.org/active_record_basics.html#convention-over-configuration-in-active-record), [GORM](http://docs.grails.org/3.1.11/guide/GORM.html#domainClasses), [Hibernate](http://docs.jboss.org/hibernate/orm/5.2/quickstart/html_single/#tutorial_annotations), etc. Classes should be named after the table, and replacing under_scores with CapitalizedNames.

We can either:
1. Liquibase update the database to match the scala names
2. Update the scala to match the database naming
3. Ignore the issue and not have a naming convention

Updating the scala seems like the least intrusive, avoiding any possibly time consuming database migrations and index rebuilding at the moment.

However, developers may have put more effort into naming the scala tables and less into the sql tables. Liquibase updates could follow as part of a future issue, if/when the schema needs other modifications.

### PR DESCRIPTION
**Pull request by kshakir**
Now setting config directly in the `database` stanza.
Deprecated `database.config`.
Database migration now just uses the key `database.migration` for configuration settings.
Moved database migration defaults into the reference.

### CODE REVIEW

**Comment by geoffjentry** [comment]
Is this pretty much just moving stuff around and renaming stuff?

**Comment by geoffjentry** [comment]
👍

**Comment by cjllanwarne** [comment]
Assuming you didn't stowaway any other changes, I'm happy if centaur's happy. 👍

**Comment by cjllanwarne** [comment]
FYI, `travis-ci/push` has found a schema mismatch. Not sure why `travis-ci/pr` failed to find it...?

**Comment by cjllanwarne** [comment]
Interestingly, @francares's PR also has a red on `push` for the schema mismatch, even though he didn't change any database tables!?

**Pull request merged**
