### PR TITLE
Only try to inject a refresh_token when asked.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by geoffjentry** [comment]
👍 

Out of curiosity, how did this come up?

**Comment by kshakir** [comment]
I'm _still_ working on implementing [this](https://github.com/broadinstitute/cromwell/pull/2500#issuecomment-318533390) integration test. At the moment, the develop cromwell client won't let centaur pass bad JSON for the test.

**Comment by kshakir** [comment]
Closing PR. Verbal reviewers rejected the change. Will migrate code to centaur instead.

**Comment by mcovarr** [comment]
verbal reviewer

**Pull request closed without merging**
