### PR TITLE
Workflow failure mode tests.  Closes #1034

### LINKED ISSUE #1034: Assess/Fix/Implement Ignored Tests in WorkflowFailSlowSpec
The goal here is to look at the tests in the spec, and determine
1. does the test assess something valuable
2. if no, delete it (with an explanation in the PR)
3. if yes, either fix it up so it passes, or reimplement... whatever is more expedient

### PR DESCRIPTION
**Pull request by scottfrazer**

### CODE REVIEW

**Comment by kshakir** [comment]
👍

**Comment by Horneth** [comment]
👍

**Comment by cjllanwarne** [comment]
I'm curious how Travis was able to pass this even before #1203 was merged...? Are they unrelated?

**Comment by scottfrazer** [comment]
This has been added to the PR#1203

**Pull request closed without merging**
