### PR TITLE
AN-214 Redirect workflow existence queries from metadata to summary

### PR DESCRIPTION
**Pull request by aednichols**
### Description

We make this query constantly, looks like the single most frequent one against metadata. All it does is check whether the workflow ID is valid by checking whether >1 metadatum exists for it.

We already started down the path of checking summary instead of metadata, see https://github.com/broadinstitute/cromwell/pull/4617. It just makes way more sense to me to check a table with 77M rows than 36B.

```
select 
  exists(
    select 
      `CALL_FQN`, 
      `METADATA_KEY`, 
      `WORKFLOW_EXECUTION_UUID`, 
      `METADATA_TIMESTAMP`, 
      `JOB_SCATTER_INDEX`, 
      `METADATA_JOURNAL_ID`, 
      `JOB_RETRY_ATTEMPT`, 
      `METADATA_VALUE_TYPE`, 
      `METADATA_VALUE` 
    from 
      `METADATA_ENTRY` 
    where 
      `WORKFLOW_EXECUTION_UUID` = '602a4913-d666-4182-b2f1-242fbda817d2'
  );
```

It is potentially implicated in the 2021 database migration that failed at the very end, you can see a bunch of them in this screenshot (2021-11-09):

Screen Shot 2021-11-09 at 1 14 03 AM

```
Lock wait timeout exceeded; try restarting transaction
  [for Statement "RENAME TABLE `cromwell`.`METADATA_ENTRY` TO `cromwell`.`_METADATA_ENTRY_old`,
  `cromwell`.`_METADATA_ENTRY_new` TO `cromwell`.`METADATA_ENTRY`"]
  at /usr/bin/pt-online-schema-change line 10922.
```
[Slack link to contemporary discussion.](https://broadinstitute.slack.com/archives/C02LCC8968N/p1636439602084200)
[Contemporary analysis in JIRA.](https://broadworkbench.atlassian.net/browse/WM-906?focusedCommentId=53394)

#### `CHANGELOG.md`
 - [ ] I updated `CHANGELOG.md` in this PR
 - [x] I assert that this change shouldn't be included in `CHANGELOG.md` because it doesn't impact community users

#### Terra Release Notes
 - [ ] I added a suggested release notes entry in this Jira ticket
 - [x] I assert that this change doesn't need Jira release notes because it doesn't impact Terra users

### CODE REVIEW

**Comment by aednichols** [comment]
Note:

As it stands, this PR could return false positives for a workflow that has been archived from metadata but still has a summary. I think this is already true for the function converted in https://github.com/broadinstitute/cromwell/pull/4617

I'm not sure whether it's a problem per se, but certainly notable.

**Comment by mcovarr** [comment]
Serious cobwebs here, but could there be false negative issues here if metadata rows exist for the workflow but a summary row hasn't been created for it yet? Like if a workflow is submitted and status is polled shortly thereafter.

**Comment by aednichols** [comment]
We definitely have had complaints about the existing code that a just-submitted workflow returns a 404 on status endpoint. But Terra doesn't care because Rawls polls every 3 minutes or whatever and it catches up.

The summarization interval is 1 second, both by default and in Terra. So the window for issues would be extremely small.

**Comment by salonishah11** [comment]
>As it stands, this PR could return false positives for a workflow that has been archived from metadata but still has a summary.

@aednichols since we ran out of time mobbing meeting earlier today, what do you think about adding a `status` check in the query for this situation?

**Comment by aednichols** [comment]
@salonishah11 it looks like we are already doing an archive status check immediately after the existence check:

https://github.com/broadinstitute/cromwell/blob/6e212299af22c9a3d5cf38d6d518afdcb61ce524/engine/src/main/scala/cromwell/webservice/routes/MetadataRouteSupport.scala#L240-L249

Today on Prod when I open the page for an archived workflow like [this one](https://app.terra.bio/#workspaces/broad-firecloud-dsde/CanaryTest/job_history/61157341-8d2f-4a15-bc6e-e67104c8eab8/63ac4bc1-388c-430d-86f5-d123a7073e3c) (canary workspace) Cromwell responds with the following JSON:

```
{
    "id": "63ac4bc1-388c-430d-86f5-d123a7073e3c",
    "message": "Cromwell has archived this workflow's metadata according to the lifecycle policy. The workflow completed at 2023-08-30T16:39:09.168Z, which was 36384533045 milliseconds ago. It is available in the archive bucket, or via a support request in the case of a managed instance.",
    "metadataArchiveStatus": "ArchivedAndDeleted"
}
```

It comes from `checkIfMetadataDeletedAndRespond` so it seems like the workflow is somehow passing the `validateWorkflowIdInMetadata` existence check despite being archived.

**Review by jgainerdewar — APPROVED** [review]

**Review by salonishah11 — APPROVED** [review]

**Pull request merged**
