### PR TITLE
Pass additional job details and config for monitoring_image [BA-5717]

### PR DESCRIPTION
**Pull request by dinvlad**
This PR adds `WORKFLOW_NAME`, `TASK_INPUTS`, `TASK_DISKS`, and `MONITORING_CONFIG` environment variables for `MonitoringAction` in PAPIv2 backend.

These variables are used to pass details about task inputs and disk mappings (both in JSON form), along with an image-specific config string (e.g. `project-id.dataset-id.table-id` for `quay.io/broadinstitute/cromwell-monitor-bigquery`), into the container specified through the existing `monitoring_image` option.

It also adds `bigquery.insertdata` OAuth scope, to be used for streaming monitoring data into BigQuery (@adrazhi seems to approve scope extension).
 
This PR will enable us to:
- stream monitoring data at scale into BQ (much more so than was possible through Stackdriver),
- build detailed models for prediction of runtime resource utilization, using BQ or external tools (e.g. Looker)
- easily detect runtime failure modes such as running OOM

(Please see https://github.com/broadinstitute/cromwell-task-monitor-bbq for more info on BQ use case)

However, the proposed changes are not specific to BQ (apart from the scope), and could be used for other `monitoring_image` implementations in the future, thanks to the new `monitoring_config` option for PAPIv2 backend.

**Please note**: this is an initial implementation that's **not yet ready for a merge**. For example, `TASK_INPUTS` are not serialized correctly yet. We intend to add more commits to implement it fully. However, we're soliciting early feedback and review.

Interested parties: @kshakir, @benjamincarlin, @rexwangcc, @mohawkTrail, @ruchim, @abaumann

### CODE REVIEW

**Comment by ruchim** [comment]
Hey Denis -- I'll pose the same question as I did in another open [PR](https://github.com/broadinstitute/cromwell/pull/5023)

Would you mind testing if this change is going to break for Terra and/or Green team prod? Meaning, if the user service Accounts don’t have BQ permission before setting those scopes in Cromwell, does the task fail to run?

**Comment by geoffjentry** [comment]
@ruchim I'll keep the convo here so it's centralized. To be clear, you're asking about making sure what happens if the SA does not have the appropriate role attached to their permissions? If not, I don't understand the question (specifically the use of "scope" in this context)

**Comment by mohawkTrail** [comment]
What behavior would be desired, in this case:  One required behavior would be that the workflow should still run (I presume).  Anything else?

**Comment by geoffjentry** [comment]
I'm curious - did we need to ensure that SAs had support for `monitoring.write` when you all added that in #4562? My bet is that this would have the same behavior, although perhaps not as that scope seems to be a little hidden

**Comment by ruchim** [comment]
Actually-- I'll reframe, if we merge both the PRs as is-- will it cause jobs to fail in Terra?

**Comment by geoffjentry** [comment]
And to reframe "did we need to ensure" - what I mean is I'd think that the effect would be the same, not "why didn't ppl have to verify it then but now they do" :P

**Comment by dinvlad** [comment]
@ruchim I think @geoffjentry is spot on - adding a scope by itself won't change existing behavior. It's only when the user sets `monitoring_image` to `quay.io/broadinstitute/cromwell-monitor-bigquery`, _then_ it will fail if the SA for the task doesn't have `bigquery.tables.updateData` permission on the monitoring dataset.

So existing users on Terra won't be affected, unless we start routinely adding that option to all workflows and don't adjust the IAM permissions on pets.

**Comment by geoffjentry** [comment]
@dinvlad In my PR (#5023) the intention was to allow users to be able to interact with BQ from inside their WDL commands. With that in mind I believe what you're suggesting is that nothing untoward would happen unless they did this and their service account didn't have the corresponding permission set. Is that correct?

I still think it's worth testing to be sure but since it looks like we've added scopes before w/o issue I'm less fearful .... but IMO there's still a risk and we should make sure the risk is 0.

Denis - it's on my list to poke at this but if you all don't want to wait for me and would like to validate success/failure please feel free to do so

**Comment by dinvlad** [comment]
Thanks @geoffjentry - that's a very welcome PR! I'll comment there, so we could address BQ scopes in your PR instead.

**Comment by dinvlad** [comment]
Re the PR, I'm re-working it to pass all of the task call-specific monitoring info (workflow name/id, task call name/index/attempt, `inputs`, `disks`, and the opaque `monitoringConfig` string) through a JSON config file on GCS (thanks @kshakir for the idea!). This way, we no longer have to use environmental variables, and can pass much more data than can be held in a variable (looking at you, `inputs`!).

That still has a potential problem of running against the API quota for GCS, but since we already access multiple files from that execution bucket inside the task, the assumption is that accessing one extra file won't hurt.

However, I'm unsure if we should just get rid of all of the environmental variables in favor of one that points to the GCS URL of the JSON config, or should we keep them (and thus duplicate information) for backwards compatibility. AFAIK, hardly anyone used this feature yet, especially given that the current "official" `monitoring_image` has been essentially broken, because Google decided to start failing Stackdriver Monitoring requests if they are submitted more than 1/minute, for a given time series. We should fix the `monitoring_image` separately (or replace it with the BigQuery version), but the question remains whether we still want to keep those env vars around for that previous use case (for anyone who might've been using a custom `monitoring_image` already).

**Comment by aednichols** [comment]
Hi @dinvlad - are you actively working on this PR? Is it still relevant in light of Jeff's PR?

Just trying to keep our PRs moving towards a terminal status (merged or closed).

**Comment by dinvlad** [comment]
@aednichols this PR is currently blocked, as I have a few questions I’m hoping to resolve with your team’s help, once you have time. The PR Jeff merged is very welcome, but it only solves a tiny portion of this one. As such, I’ve reverted the scope commit from it, so its only concern now is being able to pass additional information to the monitoring task.

If you’d prefer the questions to be raised here instead, please let me know.

**Comment by dinvlad** [comment]
Closing, since we've implemented Cromwell metadata export via a Cloud Function. For details, see https://github.com/broadinstitute/cromwell-task-monitor-bq

**Pull request closed without merging**
