### PR TITLE
More tests for conf and db

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1: a comment in the tests as to why we want to test those things would be awesome

**Comment by geoffjentry** [comment]
👍 - for my own edification I'm curious if this is something which actually bit you (and what was the symptom) or is it just purity?

**Comment by kshakir** [comment]
The conf issue was discovered while reviewing the merged reference.conf with Kate. I was showing her the difference between reference and application confs. We noticed that cromwell's reference conf was attempting to override a value and silently failing.

The db tests were just extra tests on top of the emergency fix from last friday. After the actual fix, I thought I'd add tests showing why the SqlConverters were converting empty lobs to nulls. While there, I put in a test showing a slick deadlock also.

**Comment by geoffjentry** [comment]
@kshakir Cool. I forgot that there were two types of tests, was asking about the conf one.

**Pull request merged**
