### PR TITLE
Fix bcbio test bcbio_somatic

### PR DESCRIPTION
**Pull request by aednichols**
Succeeded on this branch at https://gotc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-cron-papiv2/230/ (VPN required)

This test is identical to the one in the test_bcbio_cwl repo.

### CODE REVIEW

**Comment by danbills** [comment]
Not trolling but is there really anything to review here?  Seems like this is a "fix the test by making it current" and that means importing Brad's work.  I.e. there are no judgement calls being made here by the author @aednichols for me to review

**Comment by aednichols** [comment]
@danbills you're right, this one is pretty much a rubber stamp thumb to enable merging

**Comment by aednichols** [comment]
I suppose there's also a chance you might want to examine the console output in Jenkins to see if it looks reasonable (i.e. not succeeding for the wrong reason)

**Comment by geoffjentry** [comment]
@danbills we do still need pullapprove to go green prior to merging

**Pull request merged**
