### PR TITLE
Closes #571

### LINKED ISSUE #571: WorkflowActor derives backend from WorkflowDescriptor

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by cjllanwarne** [comment]
:+1:

**Comment by mcovarr** [comment]
looks like `compile:test` is broken?

**Comment by Horneth** [comment]
The `RetrybaleCallsSpec` is broken again because we can't give a WorkflowActor a custom backend anymore...
I'll try to find another workaround

**Comment by mcovarr** [comment]
:+1:

**Pull request merged**
