### PR TITLE
Added '/api' to readme.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by mcovarr** [comment]
This is DSDEEPB-1791

**Comment by mcovarr** [comment]
:+1:

**Comment by kshakir** [comment]
Just needs one more thumb. [Bueller?](https://listenonrepeat.com/?v=f4zyjLyBp64)

**Comment by geoffjentry** [comment]
:shipit:

**Comment by scottfrazer** [comment]
:+1:

**Pull request merged**
