### PR TITLE
WX-1445 Update docker image regex to handle python:3 correctly

### PR DESCRIPTION
**Pull request by jgainerdewar**
Update the Docker image regex to expect port numbers to have 4 or 5 digits. Interested in thoughts on this approach, because it's not bulletproof in either direction:
 * 1-3 digit port numbers are technically possible, though I've never observed one associated with a Docker repo
 * 4-5 digit numeric image tags are technically possible

If this doesn't feel like a safe solution, I can take a stab at a more aggressive update to this regex.

### CODE REVIEW

**Review by aednichols — COMMENTED** [review]
I do appreciate the small scope of this change.

Would it be difficult to support the default port 443 in case someone specifies it explicitly? Apparently Docker pulls images over regular old HTTPS.

**Review by THWiseman — APPROVED** [review]
Seems fine! Definitely not bullet proof, but also a definite improvement over what we had before. I worry about weird behavior with monotonically increasing image tags (`440, 441, 442, ERROR, 444`), but that situation seems less likely than `python:3`

**Review by aednichols — APPROVED** [review]
Proactively thumbing in case the answer to my question is, "too much work to be worth it".

PR is clearly already an improvement over what we have now.

**Review by aednichols — APPROVED** [review]
Proactively thumbing in case the answer to my question is, "too much work to be worth it".

PR is clearly already an improvement over what we have now.

**Pull request merged**
