### PR TITLE
Diet jq

### PR DESCRIPTION
**Pull request by danbills**
alpine-based image is ~ 4 MB, whereas the one we use is ~ 1 GB.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Seems like positive progress... 👍

**Comment by mcovarr** [comment]
Not sure about switching from the canonical repo to an unknown source for something like this. Also it might be nice to upgrade from jq 1.5 to the 1.6 that was released a couple of months ago if we're going to change this.

**Comment by danbills** [comment]
Is there something about 1.6 that is desirable?  

If we are very concerned I don't mind publishing our own

**Comment by cjllanwarne** [comment]
@mcovarr I had the same thought but then `"stedolan/jq:latest"` didn't seem any more official to me than what we replaced it with

**Comment by danbills** [comment]
closing this and opening a new one when I get time to figure out the best way to publish a docker image from our end

**Pull request closed without merging**
