### PR TITLE
Added Docker support to HtCondor backend. Closes #884

### LINKED ISSUE #884: Add docker support to HtCondorBackend

### PR DESCRIPTION
**Pull request by francares**
- Added docker support to HtCondor backend without the idea of using HtCondor universe.
- Added Cpu, Memory, Disk, DockerWorkingDir and DockerOutputDir runtime attributes.

Formal reviewers: @gauravs90 and @geoffjentry.

### CODE REVIEW

**Comment by gauravs90** [comment]
@francares Can you update the story on waffle (#884) and move it to in-review?

**Comment by geoffjentry** [comment]
👍

**Comment by jainh** [comment]
:+1:

**Comment by gauravs90** [comment]
👍

**Pull request merged**
