### PR TITLE
Updated GCR integration test to check for additional errors.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by kshakir** [comment]
Anyone feel free to review, but the all knowing wheel hath chosen @cjllanwarne and @geoffjentry

**Comment by geoffjentry** [comment]
The wheel seem to knoweth that I'm already online :)

**Comment by geoffjentry** [comment]
:+1: 

I am curious though if there's any concern if the 403 change is due to the test doing something wrong. I'm also a little leery that this is tied to DSDEEPB-2361 somehow. If you think it might be can you make a note on that ticket regarding this code change?

**Comment by kshakir** [comment]
Don't think it's related, but I've been wrong many times before. Left a pointer in the ticket.

**Comment by cjllanwarne** [comment]
LGTM :+1:

**Pull request merged**
