### PR TITLE
Emit the log path for the travis centaur

### PR DESCRIPTION
**Pull request by geoffjentry**
Currently running travis to make sure it works

### CODE REVIEW

**Comment by geoffjentry** [comment]
Here's what it looks like: 
screen shot 2016-08-11 at 2 55 22 pm

**Comment by mcovarr** [comment]
:+1: Looks like it would be unduly painful to capture the actual workflow ID and embed it into the URL.  This is a big improvement over scrolling back into HipChat history.  😄

**Comment by ruchim** [comment]
👍 looks clear!

**Comment by geoffjentry** [comment]
I'm going to take a quick stab at grabbing the WFID, a thought I had last night is it'd be badass to suck down the centaur log and emit it directly. If it is indeed a pain I'll just merge this for now

**Comment by geoffjentry** [comment]
14c0f057abec6dabfc5be48cbbd0d904fef889a8781eee667984089207daf998
screen shot 2016-08-12 at 5 32 31 pm

**Comment by mcovarr** [comment]
sweet!

**Pull request merged**
