### PR TITLE
Remove engineFunctions from WorkflowDescriptor.  Closes #523

### LINKED ISSUE #523: Move engineFunctions off WorkflowDescriptor to Backend

### PR DESCRIPTION
**Pull request by scottfrazer**

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Review by @kshakir and @gauravs90 please!

**Comment by kshakir** [comment]
:+1:

**Comment by gauravs90** [comment]
Probably need to rebase, but looks good

**Comment by gauravs90** [comment]
:+1:

**Pull request merged**
