### PR TITLE
Support for "Shared VPC"

### PR DESCRIPTION
**Pull request by KevinDuringWork**
Including a new setting under _"virtual-private-cloud"_ to support the **host project** in a _shared vpc environment_ and detailed here: https://cloud.google.com/vpc/docs/shared-vpc. Currently validating in our own environment.

### CODE REVIEW

**Comment by kv076** [comment]
@KevinDuringWork Were you able to validate this work before. Is your team utilizing this?

**Comment by KevinDuringWork** [comment]
This pull-request may be a little outdated (see conflict). But we're running this at my work. 

The solution may need to discussed/documented further as we're essentially introducing another a separate project-id into the configurations.

**Comment by kv076** [comment]
@KevinDuringWork: would you be willing to work with the team here to look at how we introduce this into the main branch and allow easier updates for you and others?

**Comment by KevinDuringWork** [comment]
Closing pull request - opening another one more caught up with the latest develop branch.

**Pull request closed without merging**
