### PR TITLE
fix write_* functions used as part of declarations.  Closes #613

### LINKED ISSUE #613: write_* functions not working in declarations

### PR DESCRIPTION
**Pull request by scottfrazer**
Jose ran into this issue, I investigated and found a simple fix for some of the issues.  This does not solve all issues around using `write_` functions (see https://github.com/broadinstitute/wdl4s/issues/20)

### CODE REVIEW

**Comment by cjllanwarne** [comment]
This looks like it also closes cromwell/wdl4s#20 (or relies on it already working?)

**Comment by scottfrazer** [comment]
Surprisingly this is actually a different issue

**Comment by cjllanwarne** [comment]
:+1:

**Comment by Horneth** [comment]
:+1:

**Pull request merged**
