### PR TITLE
Efs fixes for #5468

### PR DESCRIPTION
**Pull request by nvanaja**
The fixes made for #5468  broke things for EFS backend. This checkin makes sure that AWS backend works as before for both S3 and EFS.

### CODE REVIEW

**Comment by nvanaja** [comment]
@aednichols When I tried creating a branch in broadinstitute/cromwell as suggested by you in #5807,  I get 

> fatal: Authentication failed for 'https://github.com/broadinstitute/cromwell.git/' 

I did  _git push mainRepo EFS-fixes-for-5468_

**Comment by aednichols** [comment]
@nvanaja I re-verified your permissions and they look right.

I am noticing that Git is using `https://github.com/broadinstitute/cromwell.git/'` as the remote; using an HTTPS remote does not use your SSH keys for authentication and could be causing the problem.

I always recommend SSH remotes e.g. `git@github.com:broadinstitute/cromwell.git`

**Comment by nvanaja** [comment]
@aednichols thanks, that worked.

**Comment by kshakir** [comment]
Can this PR be closed? I believe comments are being tracked on the other PR

**Comment by nvanaja** [comment]
covered by https://github.com/broadinstitute/cromwell/pull/6157

**Pull request closed without merging**
