### PR TITLE
Update build sbt to 0.18

### PR DESCRIPTION
**Pull request by Horneth**
RC branch for 0.17 is here https://github.com/broadinstitute/cromwell/tree/release-0.17

### CODE REVIEW

**Comment by mcovarr** [comment]
Is there a particular motivation for this change?

**Comment by Horneth** [comment]
https://broadinstitute.atlassian.net/wiki/display/DSDEEPB/Cromwell+Release

**Comment by cjllanwarne** [comment]
Are there any other changes which will have to be wrapped up in the RELEASE 0.17 umbrella?

**Comment by cjllanwarne** [comment]
Also, this is going to be 0.17 so the original version was correct.. maybe we should update the doc to update the SBT version on the first Develop commit AFTER branching?
:-1:

**Comment by geoffjentry** [comment]
@cjllanwarne :us:

**Comment by kshakir** [comment]
:+1:

**Pull request merged**
