### PR TITLE
Remove some very large and hopefully not very necessary metadata indexes.

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Comment by geoffjentry** [comment]
is this a zero downtime migration?

**Comment by mcovarr** [comment]
@geoffjentry good question 🙂

**Comment by geoffjentry** [comment]
@mcovarr worth figuring out as any non-trivial downtime is going to be met with a giant "no"

**Comment by mcovarr** [comment]
This is currently plan A for addressing the 10 TB database limit. Plan B would definitely have non-trivial downtime.

**Comment by gemmalam** [comment]
Yesterday, in standup, it was agreed that this is unblocked. Can this be merged? @mcovarr

**Pull request merged**
