### PR TITLE
Go back to MemorySize

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by mcovarr** [comment]
This is just a revert of a previous commit?

**Comment by kshakir** [comment]
Partial revert of https://github.com/broadinstitute/cromwell/pull/3697

**Comment by kshakir** [comment]
34_hotfix version https://github.com/broadinstitute/cromwell/pull/3952

**Comment by kshakir** [comment]
Pullapprove be damned. Merging!

**Pull request merged**
