### PR TITLE
Swagger UI, back from the dead.

### PR DESCRIPTION
**Pull request by mcovarr**
In the course of working on DSDEEPB-1385 I noticed the Swagger UI had disappeared from Cromwell, but apparently we want it back now even in our world of federated Swagger.

### CODE REVIEW

**Comment by geoffjentry** [comment]
Some might say posthumously commissioned

**Comment by cjllanwarne** [comment]
:+1:
I've made a note of this PR # - presumably doing this for Thurloe will be 95% copy/paste.

**Comment by geoffjentry** [comment]
I'm guessing this wouldn't make sense for lenthall, anyone disagree?

**Comment by cjllanwarne** [comment]
@geoffjentry there's a big "this should be in Lenthall" TODO in the middle of it :)

**Comment by mcovarr** [comment]
I hope at least some of this can be moved to Lenthall, though that could drop Lenthall coverage below 100% :cry:

**Comment by kshakir** [comment]
Couldn't get oauth to work on localhost or local.broadinstitute.org, but wasn't needed for current tests. I we need auth in the future, could be interesting.

:+1: and merging.

**Pull request merged**
