### PR TITLE
Swagger needs to get a 200 on all OPTIONS calls.

### PR DESCRIPTION
**Pull request by jacarey**
Should be the last piece needed to get swagger ui working.

### CODE REVIEW

**Comment by geoffjentry** [comment]
I made one minor syntactic edit, but otherwise :+1:

**Comment by cjllanwarne** [comment]
So apparently with 200 we should be returning (at least) an Allow header with a list of available HTTP verbs per endpoint. Looking around the internet (google, reddit, github, bbc), a 405 Method Not Allowed seems to be the standard "I can't be bothered to implement content for this HTTP verb that's never used" response.

But, on the other hand, if this is just there to Make Swagger Work and it needs to be 200, then :+1:

**Comment by jacarey** [comment]
I just implemented what Agora agreed upon.  This is just for swagger and we didn't want to put any more effort into getting it to work.

**Comment by cjllanwarne** [comment]
Ok, sounds good. Thumbs up from me :+1:

**Pull request merged**
