### PR TITLE
Fix SFS hard linking

### PR DESCRIPTION
**Pull request by mcovarr**
🙈

### CODE REVIEW

**Comment by cjllanwarne** [comment]
ToL: is it possible to test that this doesn't unfix itself in the future?

**Comment by cjllanwarne** [comment]
Looks pretty show-stopping... how did we not hit this before (because we don't usually hard link?)

**Comment by mcovarr** [comment]
Jeff and I have been hitting this nonstop, we just didn't realize what it was saying. 😬 It's SFS only so that limits the visibility.

**Comment by geoffjentry** [comment]
Yeah, I didn't notice it until I started having trouble due to our VM shenanigans over the weekend and at that point I was thinking it was an artifact of all that

**Comment by mcovarr** [comment]
Detritus still errors on hard linking, I think we may not have created the execution directory first.

**Comment by mcovarr** [comment]
It looks like Chris is going to get his wish for tests since this fix seems to have broken some of the existing SFS hard linking tests. 😮

**Comment by mcovarr** [comment]
Needs more investigation. Something is definitely not right here but not sure this is it.

**Comment by mcovarr** [comment]
So it appears my proposed changes here fixed call cache hit copy hard linking (except for detritus) but broke input localization hard linking. More investigation needed...

**Pull request closed without merging**
