### PR TITLE
Fixing broken abort functionality [0.18]

### PR DESCRIPTION
**Pull request by scottfrazer**

### CODE REVIEW

**Comment by scottfrazer** [comment]
Short one needed for 0.18, @mcovarr and @Horneth

**Comment by mcovarr** [comment]
same README comment as in the other, otherwise :+1:

**Comment by Horneth** [comment]
:+1:

**Comment by scottfrazer** [comment]
@mcovarr README updated, wording okay?

**Comment by mcovarr** [comment]
:+1: sorry I didn't do that when I was cleaning it up before

**Pull request merged**
