### PR TITLE
Fix again

### PR DESCRIPTION
**Pull request by Horneth**
Only fixes this one test (hopefully).
Once the - vs _ battle settles we can act accordingly.
A few things to consider are:

- ~most of our settings in application.conf are -

- All akka/spray conf settings are -

- All our workflow options are _

- There can be no - in wdl

### CODE REVIEW

**Comment by cjllanwarne** [comment]
cf. DSDEEPB-2915

**Comment by cjllanwarne** [comment]
:+1:

**Comment by Horneth** [comment]
@geoffjentry Could you pls check that the test passes on this branch for you ?

**Comment by Horneth** [comment]
@geoffjentry @cjllanwarne Please tell me this one works !

**Comment by cjllanwarne** [comment]
Works on my laptop!

**Comment by geoffjentry** [comment]
It works! 

Now everyone back away slowly, don't breathe, and never update develop ever again

**Comment by pgrosu** [comment]
Glad to hear you guys got it all working again!

**Pull request merged**
