### PR TITLE
Allow for a 'name-for-call-caching-purposes' to override the backend name.

### PR DESCRIPTION
**Pull request by mcovarr**
Appears to work in local testing: I can rename my backend to any goofy name I want and call caching still works as long as `name-for-call-caching-purposes` is set to whatever the backend name used to be. Still working on the whole PAPI upgrade Centaur test thing and needs docs obvs.

### CODE REVIEW

**Comment by ruchim** [comment]
Also connected to #4462

**Comment by mcovarr** [comment]
@Horneth Yes I'll try that, I don't think it should be too bad...

**Comment by cjllanwarne** [comment]
Could you add this to all the backends in the `reference.conf` and `cromwell.examples.conf` to demonstrate it in use?

**Comment by mcovarr** [comment]
Temporarily closing as the centaur test is very much under construction.

**Pull request closed without merging**
