### PR TITLE
Split out hashing functionality from WdlValue proper.

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Comment by geoffjentry** [comment]
:100: / :100:

**Comment by mcovarr** [comment]
I believe the one Travis failure is unrelated, an intermittent failure in SprayDockerRegistryApiClientSpec.scala that might be a GCR hiccup?

**Comment by geoffjentry** [comment]
That one was being finicky prior to break but I don't recall why. I remember someone saying it wasn't real but dint remember the reason

**Comment by kshakir** [comment]
`SprayDockerRegistryApiClientSpec` is finicky. Should probably me marked as an `CromwellSpec.IntegrationTest`. It was already using `org.scalatest.concurrent.IntegrationPatience`.

**Pull request merged**
