### PR TITLE
[DONT MERGE] Pluggable Backend against Develop

### PR DESCRIPTION
**Pull request by cjllanwarne**
To give people a lot more sight on the big architectural change which Intel have been working on, and see just how different it really is.

Let's review the changes, make sure it meets the high Cromwell standards and try to review/guide the development to make sure this big architectural change gets done right for both sides.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Could you quickly demonstrate how to make the JES backend as a pluggable backend to this? i.e. which existing Backend functions map to which functions in the new architecture?

**Comment by francares** [comment]
This is wrong... The pull request should have been created taking into account "Master" branch.

**Comment by francares** [comment]
I will close it and re-open pointing to Master.

**Comment by geoffjentry** [comment]
@francares I disagree. The important thing from our perspective is what is changing and that means tracking develop. That the branch is off of master is somewhat orthogonal because doing a PR that way ignores the other implicit changes which are occurring

**Comment by francares** [comment]
@geoffjentry I reopened the PR. Please refer to the other PR for my comments about this.

**Comment by cjllanwarne** [comment]
@francares @geoffjentry I'm going to close this version of the PR. The comments are all heading to the other PR and Master will be updated in about a week anyway when we publish 0.17. 

At that point, the Master PR will essentially be equivalent to this one.

**Pull request closed without merging**
