### PR TITLE
Allowed the CallActor to receive an updated abort function

### PR DESCRIPTION
**Pull request by cjllanwarne**
Triggered by investigation of DSDEEPB-1934.

This caused problems in the past but I was unable to recreate a situation where a backend would update an abort function mid-call.

Even if our backends no longer update abort functions mid-call, there's no reason not to allow it for potential future backends.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
The wheel has chosen @kshakir for first reviewer.

**Comment by mcovarr** [comment]
This looks correct, but what are the circumstances under which you're seeing this?

**Comment by cjllanwarne** [comment]
@mcovarr I investigated as part of the ticket. I wasn't able to recreate the problem but I couldn't see why the option to update the abort function should be disallowed.

**Comment by mcovarr** [comment]
ok.  I have only seen this in the wild when JES "backwarded" a call status, and I didn't want to bury the symptom.

**Comment by cjllanwarne** [comment]
@mcovarr I've left the update enabled but added a new warning. So hopefully it's at least as vocal and warn-y as before but won't outright ignore the updated abort function.

**Comment by mcovarr** [comment]
:+1:

**Comment by kshakir** [comment]
:+1: on the current changes. Would love to see unit tests, but haven't examined thoroughly what we have currently for `CallActor`.

**Pull request merged**
