### PR TITLE
add a knob

### PR DESCRIPTION
**Pull request by mcovarr**
Expose an option that can be of some limited use in increasing cache hit throughput.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Please add:
 - [ ] reference.conf, 
 - [ ] README.MD
 - [ ] CHANGELOG.MD

**Comment by mcovarr** [comment]
The siblling knob is currently undocumented, I thought perhaps intentionally?  I can certainly add to the reference.conf.

**Comment by geoffjentry** [comment]
Which was the sibling? the workflow log copier?

**Comment by geoffjentry** [comment]
In terms of documenting the knob, I'm fine leaving it undocumented for now.

**Comment by cjllanwarne** [comment]
👍... but do we at least have a list somewhere (or institutional knowledge) of our undocumented options?

**Comment by kshakir** [comment]
👍

**Pull request merged**
