### PR TITLE
Unify RP error check so it also applies to singleton files [BA-6235]

### PR DESCRIPTION
**Pull request by mcovarr**
Part of a fix for BA-6235.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
I'd feel better about thumbing this with a test case

**Comment by cjllanwarne** [comment]
Though I'm as big of a fan of bunting as anyone else, I'm not sure of the relevance here:

**Comment by mcovarr** [comment]
> Bunting on review because it looks like we are adding the test in #5408

Not the type of bird usually drawn to my PRs but I'll take it indigo bunting

**Comment by aednichols** [comment]
I think I was going for the football term ["punting on something"](https://english.stackexchange.com/questions/388162/can-to-punt-something-mean-not-to-do-something) but inadvertently introduced some [baseball](https://en.wikipedia.org/wiki/Bunt_(baseball)).

**Comment by geoffjentry** [comment]
maxresdefault

**Comment by mcovarr** [comment]
Looks like the plan is to merge this before #5408 so another approval will be required

**Pull request merged**
