### PR TITLE
Return Spray timeouts as Json Closes #947

### LINKED ISSUE #947: Response timeout does not return Content-Type: `application/json`
It would be easier to consume errors if they were wrapped in JSON. I believe 400 errors are already represented this way already, but a 500 response timeout returns with Content-Type:`text/plain`.

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by geoffjentry** [comment]
I know green requested this so they'll be happy but should also let blue know as well

**Comment by kshakir** [comment]
I haven't seen the actual JSON response, but code LGTM 👍

**Comment by mcovarr** [comment]
Per @vivster7 the bug report was against 0.19 hotfix, not develop.  Not that this shouldn't be fixed here too. 😄 

@kcibul It seems #794 is also labeled 0.21 but actually applies to 0.19 hotfix.

**Comment by vivster7** [comment]
^ I would add that its not terribly important that it get fixed in hotfix, if thats what you're suggesting. Just that it gets fixed in some future version of cromwell.

**Comment by mcovarr** [comment]
Thanks @vivster7.  Do we think Blue also shares the view that this can wait for PBE?

**Comment by kcibul** [comment]
Let's keep this just on 0.20+ (PBE).  As for #794, I commented on that ticket, thanks for the heads up

**Comment by mcovarr** [comment]
:+1:

**Pull request merged**
