### PR TITLE
sbt 1.3

### PR DESCRIPTION
**Pull request by danbills**

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Applying the "do not merge" label for now, just in case turning off the awkward tests makes this go green... 🤔

**Comment by cjllanwarne** [comment]
Theory: something in the new SBT is meaning that some background thread/process is no longer shutting down the same way as before. This means that:
* (a) we get a bunch of resource leaks when `-Dsbt.classloader.close=false` is not set in the SBT options
* (b) when `-Dsbt.classloader.close=false` *is* set in sbt options, the thread remains running in the background preventing the tests from exiting on completion.

**Comment by mcovarr** [comment]
Just for reference. The linked issue sounds at least superficially similar but was closed in an earlier version. https://github.com/sbt/sbt/issues/4686

**Comment by cjllanwarne** [comment]
Based on early results from `397612a`, it seems that there really is something weird about `WorkflowDockerLookupActorSpec`

**Pull request closed without merging**
