### PR TITLE
The WDL parser is no longer part of Cromwell

### PR DESCRIPTION
**Pull request by geoffjentry**

### CODE REVIEW

**Comment by geoffjentry** [comment]
@kshakir @cjllanwarne hath been chosen by RWheel

**Comment by scottfrazer** [comment]
Should there be a corresponding PR on wdl4s to add this piece of documentation to that README?

**Comment by geoffjentry** [comment]
@scottfrazer I had it but then ended up not. I'm not sure why an outsider would want to rev the parser. I'm still really close to the fence though and could easily be swayed back to the other side.

**Comment by cjllanwarne** [comment]
+1 to keeping the command somewhere. For now, I don't have a strong opinion on documentation, build script, one-time script,... ???

Otherwise :+1:

**Comment by scottfrazer** [comment]
Also, that `hermes` command now needs to be updated for the context of wdl4s.  I can do that though if there's a PR for it on wdl4s

**Comment by scottfrazer** [comment]
https://github.com/broadinstitute/wdl4s/pull/2

**Pull request merged**
