### PR TITLE
Fixed `batch-size` config parameter name in `metadata-deletion` stanza for Carboniting [CROM-6229]

### PR DESCRIPTION
**Pull request by grsterin**

### CODE REVIEW

**Review by kshakir — APPROVED** [review]

**Review by breilly2 — APPROVED** [review]
👍  Looks good. This is technically a backwards-incompatible change, but it addresses a bug that anyone following the documentation would have encountered. Bringing the code in line with the documentation is the right move.

**Review by mcovarr — CHANGES_REQUESTED** [review]
as mentioned in standup, should have a note in the changelog

**Comment by cjllanwarne** [comment]
@grsterin is this one still active? LGTM but I agree with @mcovarr that a changelog note would be great

**Comment by evanbernstein** [comment]
We are no longer using carboniting as our solution for metadata, so we no longer need this PR.

**Pull request closed without merging**
