### PR TITLE
Understand if we can handle workflows with metadata of size ~999,999 without falling over [BA-6449]

### PR DESCRIPTION
**Pull request by grsterin**
Never merge this.
Need sanity checking. Testing method which I used was to run HelloWorld workflow using Cromwell built from this branch and wait for successful Carboniting (or OOM, or Cromwell starting to crumble in other ways).
Modifications made in this branch force Cromwell to copy the given number of root workflow's metadata jsons into the resulted carbonited json as if they were subworkflows.

### CODE REVIEW

**Comment by mcovarr** [comment]
Looks good, what were the results of running this to the point that Cromwell did not return a successful response?

**Comment by grsterin** [comment]
> Looks good, what were the results of running this to the point that Cromwell did not return a successful response?

It either fails with OOM or becomes totally unresponsive for a long time, while writing different kinds of timeout messages to the log (like "timeout while trying to fetch new workflows" or something like that).
Regarding number of rows, I remember that it handled 1.500.000 easily (carbonited within minute or two). I didn't look for precise upper bound, but I think that for 15.000.000 it was failing

**Comment by mcovarr** [comment]
OK thanks. So it sounds like this test is doing exactly what it was meant to do, but we have some work to do in making Cromwell resilient to this scenario.

**Comment by grsterin** [comment]
> Looks correct to me. Which environment did you use to run the tests?

I provisioned the dedicated VM of the same shape as used on prod: https://console.cloud.google.com/compute/instancesDetail/zones/us-central1-a/instances/greg-test-oom?project=broad-dsde-cromwell-dev
As a database I used a local MySql installed on the same VM.

>>Actually, that work has already been done and merged into develop.
>
>Did you try running this test case rebased onto those changes to confirm that? If not, should we consider making it a future task?

I did not. I'm a bit reluctant to create a new ticket for this, since the whole task is becoming too fine-grained. I can check this within current task.

**Comment by grsterin** [comment]
@cjllanwarne, checked works as expected:
```
2020-06-04 21:43:38,063 cromwell-system-akka.dispatchers.engine-dispatcher-29 INFO  - WorkflowManagerActor WorkflowActor-796f3949-47e6-497e-9458-59ab53a063c6 is in a terminal state: WorkflowSucceededState
2020-06-04 21:43:43,504 cromwell-system-akka.actor.default-dispatcher-56 ERROR - Carboniting failure: cromwell.services.MetadataTooLargeNumberOfRowsException: Metadata for workflow 796f3949-47e6-497e-9458-59ab53a063c6 exists indatabase, but cannot be served. This is done in order to avoid Cromwell failure: metadata is too large - 283000000 rows, and may cause Cromwell instance to die on attempt to read it in memory. Configured metadata safety limit is 1000000.. Marking as TooLargeToArchive
cromwell.services.MetadataTooLargeNumberOfRowsException: Metadata for workflow 796f3949-47e6-497e-9458-59ab53a063c6 exists indatabase, but cannot be served. This is done in order to avoid Cromwell failure: metadata is too large - 283000000 rows, and may cause Cromwell instance to die on attempt to read it in memory. Configured metadata safety limit is 1000000.
	at cromwell.services.metadata.impl.builder.MetadataBuilderActor$$anonfun$2.applyOrElse(MetadataBuilderActor.scala:283)
	at cromwell.services.metadata.impl.builder.MetadataBuilderActor$$anonfun$2.applyOrElse(MetadataBuilderActor.scala:267)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.actor.FSM.processEvent(FSM.scala:707)
	at akka.actor.FSM.processEvent$(FSM.scala:704)
	at cromwell.services.metadata.impl.builder.MetadataBuilderActor.akka$actor$LoggingFSM$$super$processEvent(MetadataBuilderActor.scala:245)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:847)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:829)
	at cromwell.services.metadata.impl.builder.MetadataBuilderActor.processEvent(MetadataBuilderActor.scala:245)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:701)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:695)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at cromwell.services.metadata.impl.builder.MetadataBuilderActor.aroundReceive(MetadataBuilderActor.scala:245)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

```
mysql> select * from WORKFLOW_METADATA_SUMMARY_ENTRY;
+------------------------------------+--------------------------------------+---------------+-----------------+----------------------------+----------------------------+----------------------------+--------------------------------+------------------------------+-------------------------+
| WORKFLOW_METADATA_SUMMARY_ENTRY_ID | WORKFLOW_EXECUTION_UUID              | WORKFLOW_NAME | WORKFLOW_STATUS | START_TIMESTAMP            | END_TIMESTAMP              | SUBMISSION_TIMESTAMP       | PARENT_WORKFLOW_EXECUTION_UUID | ROOT_WORKFLOW_EXECUTION_UUID | METADATA_ARCHIVE_STATUS |
+------------------------------------+--------------------------------------+---------------+-----------------+----------------------------+----------------------------+----------------------------+--------------------------------+------------------------------+-------------------------+
|                                  2 | 796f3949-47e6-497e-9458-59ab53a063c6 | wf_hello      | Succeeded       | 2020-06-04 21:40:10.924000 | 2020-06-04 21:43:38.055000 | 2020-06-04 21:40:10.726000 | NULL                           | NULL                         | TooLargeToArchive       |
+------------------------------------+--------------------------------------+---------------+-----------------+----------------------------+----------------------------+----------------------------+--------------------------------+------------------------------+-------------------------+
```

But there was a small bug:
```
2020-06-04 21:43:43,512 cromwell-system-akka.actor.default-dispatcher-56 ERROR - Programmer Error! The CarboniteWorkerActor cannot convert this into a completion metric: CarboniteWorkflowComplete(796f3949-47e6-497e-9458-59ab53a063c6,TooLargeToArchive)
```
I created a ticket for it: https://broadworkbench.atlassian.net/browse/BA-6471

**Comment by cjllanwarne** [comment]
@grsterin I think that will hopefully already be covered by https://broadworkbench.atlassian.net/browse/BA-6456

**Pull request closed without merging**
