### PR TITLE
* API batch endpoint handler support imports - fixes  #1753

### LINKED ISSUE #1753: API batch endpoint: support for imports?
Currently only the `workflows/:version` endpoint supports `wdlDependencies`; can we have it for `workflows/:version/batch` too? We love imports and we love the batch endpoint :smile:

### PR DESCRIPTION
**Pull request by delocalizer**

### CODE REVIEW

**Comment by cjllanwarne** [comment]
👍

**Comment by cjllanwarne** [comment]
See also for develop: https://github.com/broadinstitute/cromwell/pull/1760

**Comment by ruchim** [comment]
👍

**Comment by cjllanwarne** [comment]
We have an issue with the centaurJes tests running for external users. 

Assuming the tests go green for https://github.com/broadinstitute/cromwell/pull/1760, I think this one should be considered green too.

**Pull request merged**
