### PR TITLE
Replaced last scalaz holdout [CROM-6799]

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Review by mcovarr — APPROVED** [review]
LGTM

**Review by cjllanwarne — APPROVED** [review]
Awesome

**Comment by cjllanwarne** [comment]
Pinging @kshakir for direction... can you think of any reason for us not to merge this?

**Comment by kshakir** [comment]
Same reasons most PRs are still open:
- It doesn't have a jira ticket
- The ticket has not been refined
- The ticket hasn't been added to a sprint

**Pull request merged**
