### PR TITLE
Don't try to push wes2cromwell to DockerHub.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by salonishah11** [comment]
This is related to CI Updates PR #4169?

**Comment by kshakir** [comment]
> This is related to CI Updates PR #4169?

Yes.

Cromwell's various libraries and executables are only pushed on develop & hotfix branches, well after one has merged changes in a PR. A number of times PR have been unknowingly breaking the develop/hotfix builds.

After I confirmed that #4169 helped develop's "sbt" build go green, I submitted this #4181 PR to repair the `34_hotfix` branch. #4180 is a similar PR for `35_hotfix`.

Meanwhile, #4179 is a couple of regression tests targeted at future `develop` PRs. During any `push` the "sbt" build will ensure that credentials for artifactory exist on disk, and that a docker hub repository exists for to-be-pushed executables.

**Comment by cjllanwarne** [comment]
(out of interest) - Why would we not want wes2cromwell on dockerhub? Seems like a great candidate for including in a `docker-compose` eventually?

**Comment by kshakir** [comment]
> Why would we not want wes2cromwell on dockerhub?

Can be added at any time! Someone just needs to create the repo with the right permissions.

**Comment by geoffjentry** [comment]
Also my hope is to fold it into cromwell proper in the not too distant future, doing away with the shim altogether

**Pull request merged**
