### PR TITLE
Fix minor SGE bug.  Sometimes the job ID is not on the first line.

### PR DESCRIPTION
**Pull request by scottfrazer**
This only worked if the first line contained the `Your job 1234` string.  However, sometimes there's a little warning message that appears on the first line.

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1:

**Comment by Horneth** [comment]
:+1:

**Comment by gsaksena** [comment]
-terse Available for qsub only.

              -terse causes the qsub to display only the  job-id  of  the  job
              being  submitted  rather than the regular "Your job ..." string.
              In case of an error the error is reported on stderr as usual.
              This can be helpful for scripts which need to parse qsub  output
              to get the job-id.

**Comment by scottfrazer** [comment]
Thanks @gsaksena  I'll update this code to use `-terse`

**Pull request merged**
