### PR TITLE
Metadata is more informative for unexpected return code (WORK IN PROGRESS)

### PR DESCRIPTION
**Pull request by myazinn**
The purpose of this PR is to make `/metadata` more informative, as described in #4856.
It appears that Cromwell already stores the necessary info in a `stderr.log` file. Therefore, reading the content of that file and printing to the user should be enough.
However, one thing bothers us. In the method `handleExecutionResult` of the trait `StandardAsyncExecutionActor`, the comment says that
```
Only check stderr size if we need to, otherwise this results in a lot of unnecessary I/O that
may fail due to race conditions on quickly-executing jobs.
```
But in order to give additional info to the user, we have to read the content of that file. Also, we do not understand, why this is such a big deal. The method `handleExecutionResult` must be called when the execution is finished and that file is written. What race conditions may arise and is it important in this case?

### CODE REVIEW

**Comment by cjllanwarne** [comment]
This looks remarkably similar to the change made in https://github.com/broadinstitute/cromwell/pull/4952 (and seems to re-invent the "don't read too much" logic with a slightly different maximum size).

I wonder whether it would be possible to combine the "read from stderr" logic from these two changes to always happen in the same place - even if the resulting message text then ends up going in different directions?

**Comment by myazinn** [comment]
Hi @cjllanwarne -
I pushed a new commit. Can you check it now? Tests are failing because they expect messages formatted differently. I'll fix them if you say that other things are okay.
The contents of the file are still read twice, but now the main logic is located in one method. I tried to do this with one reading, but it caused a lot of headaches :) If necessary, I can explain in more detail what problems arise when reading a file only once.

**Comment by cjllanwarne** [comment]
Hi @myazinn, sorry for the slow response time, and I haven't really looked at this in detail, but it looks like we'll now be calling the same function twice for the same stderr file (once for the job message and once for the workflow message)? Is that right?

What I mean is, when a task within a workflow fails, do we now download the same stderr file twice?

**Comment by myazinn** [comment]
Hi @cjllanwarne 
You are right, the file is indeed read twice. This is because there is a problem with reading it only once.
The metadata that the user sees is taken from the `getMessage` method of the exception (at least right now it's done that way). This means that the error file must be read when creating the `WrongReturnCode` exception and this information must be embedded in the exception object.
In the meantime, [`expandFailureReasons`](https://github.com/broadinstitute/cromwell/blob/c45343ec33f922c9784667a9aa1d42ed68f8c9ba/engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala#L323) tends to add the content of the error file to every `KnownJobFailureException` exception (`WrongReturnCode` is the subclass of it). This means that if we want to get rid of double reading an error file, we must read this file at the moment the exception is created. In that case, the `expandFailureReasons` will have guarantees that there is no need to read it again.
The ideal solution is to let every `KnownJobFailureException` read the error file automatically during creation. This would have solved the metadata issue and eliminated the need to read the file in the `expandFailureReasons`.
But there is a huge problem. Reading the error file requires an execution context. Which means creating such an exception would require an execution context. This may break existing code.
That is the essence of a problem. In order not to read the file twice, the `expandFailureReasons`  method needs guarantees that the file has already been read. To give these guarantees, we need to change the signature of the exception constructor. But it may break existing code.
Although there is a workaround. I can add an `optionalErrorMessage` field to the  `KnownJobFailureException` exception with the default value `None`. The `expandFailureReasons` method will check whether this field `Some` or `None`, then it will read the file only if it is `None`. This is ugly, but it will work.
I hope I gave you an understanding of a problem. Maybe you can give me some advice?

**Comment by geoffjentry** [comment]
@myazinn OOI is this still considered a work in progress?

**Comment by myazinn** [comment]
@geoffjentry Yes, it is. I would like to do something with it. But I don't know which solution to this problem is better in your opinion.
However, if you don't have any ideas and think that this way to solve it is completely wrong then I think I must close this PR.

**Comment by aednichols** [comment]
Do you have an example before & after?

It seems like the output would contain `[First $limitBytes bytes]` from `annotatedContentAsStringWithLimit` which is a pretty strange thing to have in the middle of an error message.

**Comment by myazinn** [comment]
@aednichols 
Yeah, it seems pretty ugly. Implementing it less ugly may require some refactoring and I'm not sure that I can do it in the right way. I think it would be better to close this PR and leave this issue to someone who knows Cromwell better than me.

**Pull request closed without merging**
