### PR TITLE
Oops, these PostMVPs should all be ignored

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

**Comment by cjllanwarne** [comment]
For benefit @kshakir and @kcibul, please review!

**Comment by Horneth** [comment]
I though the advantage of tagging them was that we could exclude them from "sbt test" while still having them "unignored" so they don't count against the "ignored" count.

**Comment by kshakir** [comment]
Assuming `PostMVP` tagged tests are filtered out of `sbt test`, then they should never be _added_ to the ignored count. This patch therefore only adds to the ignored count for `sbt alltests:test`.

**Comment by kshakir** [comment]
👍

**Comment by mcovarr** [comment]
:+1:

**Comment by kcibul** [comment]
I think you've got your thumbs, but you've got my 👍 as well!

**Pull request merged**
