### PR TITLE
Added a seq function to Cromwell's WDL interpretation.

### PR DESCRIPTION
**Pull request by cjllanwarne**
From dog-fooding array creation in WDL.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Would appreciate any instructions on where to document this (if at all!)

**Comment by cjllanwarne** [comment]
Allows WDL code like:
```
  Array[Int] indexing_list = seq(5)

  scatter (idx in indexing_list) {
    call FileSpam { input: index = idx, width = 5 }
  }
```

it's also annoying that you can't also put the seq(5) inline, but that's a separate, existing ticket

**Comment by Horneth** [comment]
I'd say here https://github.com/broadinstitute/wdl/blob/develop/SPEC.md
And also add it here https://github.com/broadinstitute/wdl4s/blob/d7e19c9f4dfbc5ad912cf641af9c640eb8a9a9c7/src/main/scala/wdl4s/expression/WdlStandardLibraryFunctions.scala

**Comment by cjllanwarne** [comment]
@Horneth - after talking to @scottfrazer I was hoping to avoid this requiring a WDL4S change (i.e. and therefore let it be a Cromwell custom function rather than a core feature of the WDL spec)

**Comment by scottfrazer** [comment]
I'm certainly not opposed to it being an official function in WDL if you want it to be!  If not, it can be a hidden feature :)

**Comment by Horneth** [comment]
Ok for me either way !

**Comment by scottfrazer** [comment]
👍

**Comment by Horneth** [comment]
👍

**Comment by geoffjentry** [comment]
@cjllanwarne So is this like python's range? The simple form at least. If so I wonder if that'd be a more obvious name for it in terms of the primary wdl userbase

**Pull request merged**
