### PR TITLE
Add `sep` function for joining array of strings

### PR DESCRIPTION
**Pull request by illusional**
Relevant OpenWDL PR: ~~https://github.com/openwdl/wdl/pull/229~~ (rebased into) https://github.com/openwdl/wdl/pull/366

Adding a `sep` function to join arrays of string together.

I've followed the general process from: https://github.com/broadinstitute/cromwell/pull/4409/files,

---

### Older discussion that has been resolved

Getting two errors, but not really sure why,  but really having problems with the `sepFunctionEvaluator`, it's a two value function so I tried to use the `processTwoValidatedValues` from `wdl.transforms.base.linking.expression.values.EngineFunctionEvaluators`, but I'm getting errors on the evaluateValue:

```scala
val value1 = expressionValueEvaluator.evaluateValue(a.arg1, inputs, ioFunctionSet, forCommandInstantiationOptions)(expressionValueEvaluator)
val value2 = expressionValueEvaluator.evaluateValue(a.arg2, inputs, ioFunctionSet, forCommandInstantiationOptions)(expressionValueEvaluator)
processTwoValidatedValues[WomArray, WomString, WomString](value1, value2) { (arr1, sepvalue) =>
    EvaluatedValue(WomString(arr1.value.mkString(sepvalue.value)), Seq.empty).validNel
}
```

But I get the following error:

```
[error] /Users/franklinmichael/source/cromwell/wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/BiscayneValueEvaluators.scala:164:64: type mismatch;
[error]  found   : common.validation.ErrorOr.ErrorOr[wdl.model.draft3.graph.expression.EvaluatedValue[wom.values.WomString]]
[error]     (which expands to)  cats.data.Validated[cats.data.NonEmptyList[String],wdl.model.draft3.graph.expression.EvaluatedValue[wom.values.WomString]]
[error]  required: common.validation.ErrorOr.ErrorOr[wdl.model.draft3.graph.expression.EvaluatedValue[wom.values.WomArray]]
[error]     (which expands to)  cats.data.Validated[cats.data.NonEmptyList[String],wdl.model.draft3.graph.expression.EvaluatedValue[wom.values.WomArray]]
[error]       processTwoValidatedValues[WomArray, WomString, WomString](value1, value2) { (arr1, sepvalue) =>
[error]                                                                ^
[info] common.validation.ErrorOr.ErrorOr[wdl.model.draft3.graph.expression.EvaluatedValue[wom.values.WomString]] <: common.validation.ErrorOr.ErrorOr[wdl.model.draft3.graph.expression.EvaluatedValue[wom.values.WomArray]]?
```

I also tried switching this to use:

```scala
processTwoValidatedValues[WomArray, WomString, WomString](a.arg1.evaluateValue(inputs, ioFunctionSet, forCommandInstantiationOptions), a.arg2.evaluateValue(inputs, ioFunctionSet, forCommandInstantiationOptions)) { (arr1, sepvalue) =>
    EvaluatedValue(WomString(arr1.value.mkString(sepvalue.value)), Seq.empty).validNel
}
```

Gives the following error:

```
[error] /Users/franklinmichael/source/cromwell/wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/BiscayneValueEvaluators.scala:161:72: value evaluateValue is not a member of wdl.model.draft3.elements.ExpressionElement
[error]       processTwoValidatedValues[WomArray, WomString, WomString](a.arg1.evaluateValue(inputs, ioFunctionSet, forCommandInstantiationOptions), a.arg2.evaluateValue(inputs, ioFunctionSet, forCommandInstantiationOptions)) { (arr1, sepvalue) =>
[error]                                                                        ^
[error] /Users/franklinmichael/source/cromwell/wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/BiscayneValueEvaluators.scala:161:149: value evaluateValue is not a member of wdl.model.draft3.elements.ExpressionElement
[error]       processTwoValidatedValues[WomArray, WomString, WomString](a.arg1.evaluateValue(inputs, ioFunctionSet, forCommandInstantiationOptions), a.arg2.evaluateValue(inputs, ioFunctionSet, forCommandInstantiationOptions)) { (arr1, sepvalue) =>
[error]                                                                                                                                                     ^
[error] two errors found
```

NB: 

- ~~No tests for this yet.~~ There are tests.
- Resolved: I'll need to clarify `sepFunctionEvalutor` in `BiscayneTypeEvaluators.scala` to only accept an Array of Strings. I presume I just need to change the validateParamType block to be:

```scala
    validateParamType(a.arg2, linkedValues, WomArrayType(WomAnyType)) flatMap {
        case WomArrayType(WomStringType) => WomStringType.validNel
        case other => s"Cannot invoke 'sep' on type '${other.stableName}'. Expected an array".invalidNel
      }
```

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Thanks @illusional!

I ended up making a PR against your PR branch back in the `illusional/cromwell` repo with a few changes... I fixed your compile issues and added a few tests. It looks like your type evaluator is expecting a map input to the function for some reason, and doesn't like the string/array, and the value evaluator has the order of the two parameters back to front, but otherwise I think it looks fairly solid.

An end to end centaur test would probably also be a good idea.

**Comment by cjllanwarne** [comment]
My PR against your PR branch: https://github.com/illusional/cromwell/pull/1

**Comment by illusional** [comment]
You’re amazing @cjllanwarne, thanks for the help! The type system within Cromwell is definitely the thing I understand the least about, and made worse by my lack of experience of Scala.

Really appreciate you taking a look at this :)

**Comment by illusional** [comment]
Hi @cjllanwarne, to get this change closer to the (now correctly referenced WDL card), will I need to remove the option for interpolators to work for the development / Biscayne spec. Technically, it's not against the spec for Cromwell to accept it, but it might be confusing for users if it does. If so, I assume changing the grammar might be sufficient, but this would come from WDL and not Cromwell.

If I don't, I think this PR just needs more tests from me then it might be ready for review.

**Comment by cjllanwarne** [comment]
@illusional you're right, we'll also need to change the grammar in the openwdl repo to remove the parsing of placeholder attributes like `sep`, `true`, `default` in order to be 100% finished with the change. I don't think that invalidates the correctness of the changes you've made here in any way though

**Comment by illusional** [comment]
I think this is ready for review, passes my basic workflows okay.

### Testing 

Alrighty, so I did some digging and looks like similar PRs don't include tests. This doesn't mean I should blindly follow, but I can't see a great way to add a test and check its output, so I've only added validation tests (293256180ea8f6f5398866110ba8b727fd4c148e).

I'm not sure if this should make it into the CHANGELOG, but I've added some text here which I'll add into the 

> ### New sep function for joining an array of strings
>
> Per [OpenWDL #229](https://github.com/openwdl/wdl/pull/229), we've replaced the `sep=` string interpolator option with a new `sep` engine function, available in the WDL development (Biscayne) specification.

**Comment by illusional** [comment]
Hi @cjllanwarne, just bumping this PR as the new associated spec change (https://github.com/openwdl/wdl/pull/366) was merged. Thanks!

**Comment by illusional** [comment]
Thanks @aednichols!

I never even though if (1), I’ll have a look at me other PRs and make sure to do this in future :)

(2), happy to wire it up for other versions if you want?

**Comment by aednichols** [comment]
> I've given DRAFT 3 the sep function when it shouldn't have it?

Yes, precisely

**Comment by illusional** [comment]
Thanks @aednichols, I’m not sure how to make the function visible to Biscayne but not draft 3, any pointers or similar examples? Thanks :)

**Comment by illusional** [comment]
Hey @aednichols, I tested this to make sure, and as expected, running the test with `version 1.0` fails with errors:

```
Failed to read task definition at line 3 column 6 (reason 1 of 1): Failed to read outputs section (reason 1 of 1): Failed to read declaration (reason 1 of 1): Failed to parse expression (reason 1 of 1): Unknown engine function: 'sep'
Failed to read task definition at line 13 column 6 (reason 1 of 1): Failed to parse expression (reason 1 of 1): Unknown engine function: 'sep'
```

I've fixed the corresponding tests in https://github.com/broadinstitute/cromwell/pull/5494/commits/40851b7423de68bda7ff9aaa47a37fbf7a0a70a3.

So this should still be good to merge!

**Comment by illusional** [comment]
@cjllanwarne @aednichols  Looks like the tests didn’t complete with the same error, I gave merging from develop another crack without success.

Hopefully it’s all good though 😬

**Comment by aednichols** [comment]
SBT fails with an error that looks very related
```
should evaluate a sep expression containing a sub-call to prefix correctly *** FAILED *** (50 milliseconds)

[info]   EvaluatedValue(WomString(-i a -i b -i c),List()) was not equal to EvaluatedValue(WomString(a b c),List()) (ErrorOrAssertions.scala:11)

[info]   org.scalatest.exceptions.TestFailedException:
```

**Comment by illusional** [comment]
Thanks @aednichols, looks like I didn't scroll down enough - I think @cjllanwarne added this test at the very start so wasn't on my horizon to check. I've pushed a fix, and will confirm when it's fixed.

**Comment by illusional** [comment]
Thanks @aednichols, green tick against SBT now.

**Comment by aednichols** [comment]
Looking good @illusional, thanks for your contribution! Sorry to throw up another hurdle, but it would be convenient if you made a copy of your branch in the `broadinstitute` repo and made a new PR based on it. That would allow our full (costing real money) CI suite to run, because you're a Collaborator

**Comment by cjllanwarne** [comment]
Closing because we'll be merging from #5573 instead.

**Pull request closed without merging**
