### PR TITLE
fail file hashing if the file does not exist

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by ruchim** [comment]
:+1:

**Comment by geoffjentry** [comment]
👍 

Out of curiosity, what caused this to turn up?

**Comment by Horneth** [comment]
I was testing some call caching behaviors. Specifically I tried to call cache on local backend with the "hash the file path" method which would hash a file path even though the file doesn't exist. The job would then try to find a cache hit for this path even though the file doesn't exist

**Comment by andy7i** [comment]
H

**Pull request merged**
