### PR TITLE
Batch submit as a hotfix. Closes #634

### LINKED ISSUE #634: Batch submission endpoint
As a user (FireCloud) I have the use case of wanting to submit a number of workflows (~1000) that are all the same WDL with different inputs.  For example, running the same pipeline on all samples in my cohort.  Currently I have to do this with 1000 separate calls which is inefficient.

I would like a new batch submission endpoint which allows me to submit a single WDL, a single workflowOptions and an array of inputJsons.

The server will take this and create the individual submissions and return an array of workflow ids are in the same order as the submitted jsons (e.g. the first returned id will be for the workflow that uses the first supplied json and so on).

### PR DESCRIPTION
**Pull request by kshakir**
~~TODO~~ DONE:

- [x] Confirm existing spec TODOs are ok
- [x] Confirm reviewers are ok with naming
- [x] Add same patch to develop

### CODE REVIEW

**Comment by kshakir** [comment]
This should look very familiar to the thumbs of @cjllanwarne / @kcibul / @Horneth

**Comment by Horneth** [comment]
👍

**Comment by kcibul** [comment]
:+1:

**Comment by kcibul** [comment]
except for that part about the failing build :(

**Comment by kshakir** [comment]
My cherry-pick picked out too much. One more time!

**Comment by kshakir** [comment]
Going to squash and merge, even though @kcibul's thumb wasn't recognized as "pull approved"

**Pull request merged**
