### PR TITLE
5000ft view of Cromwell's actor system [WA-54]

### PR DESCRIPTION
**Pull request by salonishah11**
JIRA issue [link](https://broadworkbench.atlassian.net/browse/WA-54)

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Note: link to the docs in readthedocs: https://cromwell.readthedocs.io/en/ss_bitsize_actors/developers/bitesize/majorActorSystem/5000FtActorSystem/

**Comment by cjllanwarne** [comment]
#### Comment 1

Could you add a key to indicate what the various colors and line-types mean?

#### Comment 2

All of the actors are ultimately descended from the CromwellRootActor (or should be, except the server or cmdline actors which create it) - I don't see that shown for the call cache actors group. Is that genuinely true (scary!), or do they need a line of ancestry coming in from somewhere?

#### Comment 3 
(this one is more TOL-y...)

Is there an even higher level "10,000 foot" view with functional units shown linked together? Eg you've drawn some of the boxes in different colors, presumably those would be reasonable candidates for boxes on some higher-level view?

The reason I ask is, (a) this diagram is scarier than I realized! It'd be nice to have some higher-level context before seeing the whole thing in full... and (b) I had to zoom in really far in order to make out the words in the individual boxes - I wonder if one context-setting diagram would then let us have (say) 5 different 5,000 foot magnifications for individual subsystems, rather than a single all-in-one diagram?

**Comment by salonishah11** [comment]
@cjllanwarne Which call caching actors are you referring too? CallCacheRead and CallCacheWrite actors are descending from CromwellRootActor. Or are you talking about any other call caching actors? 🤔

**Comment by salonishah11** [comment]
@rsasch @cjllanwarne I will add a key explaining what each color represents

**Comment by cjllanwarne** [comment]
These light green ones don't seem to have any parents:

Screen Shot 2019-11-07 at 4 06 57 PM

**Comment by salonishah11** [comment]
Yes I just noticed that. They are being created in the BackendLifecycleActorFactory so I added links for that.

**Comment by salonishah11** [comment]
@rsasch @cjllanwarne I have updated the diagram and added a key. Regarding (Chris's) Comment 3, we can surely go 5000ft higher and create a 10000ft diagram. I will take a look. Somehow 10000ft higher is harder to visualize! :)

**Comment by grsterin** [comment]
I'd suggest to avoid overlapping `database interaction` arrows with arrows of other types on the diagram. Something like this:
image

Looks like something happened with the error between `ServiceRegistryActor` and `HybridMetadataServiceActor`:
image

**Comment by grsterin** [comment]
Shouldn't this be EngineJobExecutionActor?
image

**Comment by grsterin** [comment]
image
I'm still not sure what are `Execution store` and `Value store` from the picture above. Color coding suggests that they are `connected components`, but the meaning is still not clear to me. Also, maybe `connected component` is not the best term in this case, since its strong ties with graph theory?

**Comment by salonishah11** [comment]
@grsterin I have separated the database interaction arrows from other arrows. I have fixed the missing arrow between `ServiceRegistryActor` and `HybridMetadataServiceAcrtor` and the spelling for `EngineJobExecutionActor` (oops!). Regarding `ExxecutionStore` and `ValueStore`, I was not sure what exactly to call them on the key. So for lack of better words I labeled them as Connected Components. I do agree it is not the best term and I  am open to suggestions on what to call them :)

**Comment by grsterin** [comment]
> Regarding `ExxecutionStore` and `ValueStore`, I was not sure what exactly to call them on the key. So for lack of better words I labeled them as Connected Components. I do agree it is not the best term and I am open to suggestions on what to call them :)

So, my understanding is that they are some interim in-memory storages for WOM-graph related execution data. In this case, I'd call them something like "in-memory execution data storage", ot just "in-memory storage".

**Comment by salonishah11** [comment]
@grsterin I have updated the key to replace 'Connected Components' with 'In-memory Storage'.

**Pull request merged**
