### PR TITLE
Add python caches to gitignore

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

**Comment by mcovarr** [comment]
I didn't drill in but that is a lot of build failures.

**Comment by cjllanwarne** [comment]
I'd be surprised if a one-line gitignore addition would cause all those errors, which from an n of 1, seem mostly like bad travis weather... 🤞 a restart will fix these

**Comment by mcovarr** [comment]
restarts didn't seem to do the trick but a cache blast + restart is looking better

**Comment by cjllanwarne** [comment]
> a cache blast + restart is looking better

thanks!

**Pull request merged**
