### PR TITLE
Disable digest lookup to work around non-support of proxies

### PR DESCRIPTION
**Pull request by sychan**
This is a resubmission by the Joint Genome Institute of https://github.com/broadinstitute/cromwell/pull/6140 to provide an option to disable digest lookups to support private docker registries with private images. We have long running workflows at JGI that use private images which cannot take advantage of Cromwell's call caching feartures - this is blocking a major analysis workflow's migration to Cromwell. Given that JGI also has other Docker images which are non-public, it is only the first of what is likely to be many other production workflows that cannot be used with Cromwell, blocking our institutional goal of consolidating JGI analysis workflows on Cromwell as our workflow engine. 

Changelog:

Added config option docker.perform-registry-lookup-if-digest-is-provided with default True (https://github.com/broadinstitute/cromwell/commit/e9965d8f9a385b289f15b23b3fb923ecb8c0ea38)
Added logic to DockerConfiguration.scala to sendDockerRequest if performRegistryLookupIfDigestIsProvided is true, else just lookupKvsOrBuildDescriptorAndStop.
Motivation:

Cromwell only allows call-caching when a digest is provided.
The digest registry lookup fails because Cromwell isn't respecting the system proxy.
This disables call-caching, even though we've provided the digest.
From original PR:

This PR is based on a comment in the Slack, and ongoing conversation in How to configure proxies? (which stems from https://github.com/broadinstitute/cromwell/issues/5006).

Essentially, I don't want Cromwell to lookup my container when I provide it as a digest, because if the request fails (because Cromwell isn't respecting the system proxy), I still want call-caching to work. The main reason Cromwell seems to want to lookup the external registry is for the docker size which gets logged to metadata and doesn't seem to be used again.

Thanks @mcovarr for the initial feedback, and sorry it took so long to action your suggestions. I've moved this to an internal branch so tests run automatically (as suggested in the past). I've included some of your feedback (that the dockerSize is used in the Google Backends) to the reference.conf and the DockerConfiguration.scala. I haven't included it in the documentation, but it's documented in the reference.conf.

### CODE REVIEW

**Comment by aednichols** [comment]
Can you share more details about the private Docker registry? Is it self-hosted or a commercial vendor?

**Comment by sychan** [comment]
@aednichols Are there any other questions about this PR that we can answer? Any concerns that you would like to see addressed?

**Comment by aednichols** [comment]
There's something wrong with the diff compared to the [original PR](https://github.com/broadinstitute/cromwell/pull/6140), there are zero files listed.

**Comment by sychan** [comment]
@aednichols I just realized that I had specified the wrong branch for the PR. I've merged the commits into JGI-Bioinformatics:cromwell/develop

**Comment by sychan** [comment]
> Fair warning - in keeping with [my comment from February](https://github.com/broadinstitute/cromwell/issues/5006#issuecomment-1421492972), Cromwell does not support or test proxies, so there is no guarantee this PR will be a complete solution and/or that it will keep working.

Yes, I think it is understood that this is an option which originates from and is supported from outside the main Cromwell development effort.

**Comment by aednichols** [comment]
It's a bit more than that - there may be other parts of Cromwell that don't work with proxies. New such places may also appear unexpectedly due to non-testing. In other words, I strongly suggest trying to give Cromwell unrestricted Internet access first.

**Comment by aednichols** [comment]
After discussing internally, we unfortunately can't add this code or support the general direction of proxy compatibility. Docker lookups and call caching are pretty sensitive and involved and we're looking to keep the configuration surface area to an absolute minimum.

**Comment by illusional** [comment]
Hearing that the Cromwell team will reject this (and then hence the original PR) is pretty disappointing. The configuration option is specific, doesn't explicitly relate to proxies, but allows us to run Cromwell, despite the lack of proxy support.

**Comment by aednichols** [comment]
Sorry about that. The issue is focus and resources, not merit.

**Pull request closed without merging**
