### PR TITLE
Optional string concatenation

### LINKED ISSUE #5460: Cromwell is not correctly concatenating string + null + string in the command block
Created in collaboration with: @TMiguelT

The OpenWDL spec states when interpolating a string in the command block:
> Within interpolations, string concatenation with the + operator has special typing properties to facilitate formulation of command-line flags. [...] If either operand has an optional type, then the concatenation has type String?, and the runtime result is None if either operand is None.

Ie:
- `string + null + string -> null`:

That is, if `str` is not defined (`null`), the following should resolve to null and empty:
```
~{'"--prefix" "' + str + '"'}
```

Currently, it's resolving to `"` (a single double-quote).

Eg: In the task:

```wdl
version development
task quotetest {

  input {
    String? str
  }

  command <<<
      echo ~{'"--prefix" "' + str + '"'}
  >>>

  output {
    String out = read_string(stdout())
  }
}
```

A fix to this would reduce our usages of `if defined(name) then "" else ""`.

### PR DESCRIPTION
**Pull request by illusional**
Closes #5460 

Cromwell isn't correctly cascading `string + optional + string` behaviour. It seems that `string + optional` is evaluating to an empty string.

The [WDL Spec: _Interpolating and concatenating optional strings_](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#interpolating-and-concatenating-optional-strings)

> Within interpolations, string concatenation with the + operator has special typing properties to facilitate formulation of command-line flags. [...] If either operand has an optional type, then the concatenation has type String?, and the runtime result is None if either operand is None

That is, if `str` resolves to `None`, then this should resolve to `echo `. Instead this is currently resolving to `echo "` (single quote).
```
      echo ~{'"--prefix" "' + str + '"'}
```

## Example

```wdl
version development
task quotetest {

  input {
    String? str
  }

  command <<<
      echo ~{'"--prefix" "' + str + '"'}
  >>>

  output {
    String out = read_string(stdout())
  }
}
```

Without value:

```bash
java -jar cromwell-48.jar run quotetest.wdl 
# Job quotetest:NA:1 exited with return code -1
# STDERR: unexpected EOF while looking for matching '"'
```

With value:

```bash
java -jar cromwell-48.jar run quotetest.wdl -i quotestest-inp.json 
# "outputs": {
#  "quotetest.out": "--prefix Hello"
# }
```

## This PR

Addresses the spec, by:

- Changing type checker: OptionalType<T> + T => Optional<T> (within the current rules).
- Optional + String => String else None

### CODE REVIEW

**Comment by illusional** [comment]
I've added a test `string_interpolation_optional` that succeeds when I ran:

```bash
sbt "centaur/it:testOnly * -- -n interpolation"
```

I've begun the process for getting this added as a conformance test for WDL.

**Comment by illusional** [comment]
Hi @evanbernstein, thanks for adding the Community Contribution label. Just wondering what the process is to get this change approved.

**Comment by aednichols** [comment]
@illusional thanks for your contribution. Reviewing PRs is time-consuming for the team and we have the bandwidth to look at only 2-3 at once. Those are marked with the "on deck for review" label.

Best regards and thanks for your patience,
Adam

**Comment by aednichols** [comment]
Hi @illusional, we put this PR into our schedule to review, could you please make a version of it inside the repo as you did for https://github.com/broadinstitute/cromwell/pull/5573?

Thanks,
Adam

**Pull request closed without merging**
