### PR TITLE
Fix Swagger auth [BA-6185]

### PR DESCRIPTION
**Pull request by aednichols**

### CODE REVIEW

**Comment by aednichols** [comment]
Yeah, for once I talked myself out of a regex, this is just way simpler to assess correctness on

**Comment by dinvlad** [comment]
If I may suggest, let's first see if this fix works in dev, and only then merge/do the rest properly :-)

**Comment by cjllanwarne** [comment]
@dinvlad if you want to test in a dev environment it should be possible to do that immediately (ie before merging the branch)

**Comment by dinvlad** [comment]
Not sure I have the powers to push a dev image to Docker Hub though (let's discuss offline).

**Comment by aednichols** [comment]
>Jira please!

@cjllanwarne is this a preference or an actual rule that I'm not aware of? We have a lot of [no JIRA] PRs.

**Pull request merged**
