### PR TITLE
Add Nirvana 3.18.1 reference image test, minor cleanup [VS-705]

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Comment by geoffjentry** [comment]
nirvana-logo

**Comment by aednichols** [comment]
Relates to https://github.com/broadinstitute/firecloud-develop/pull/3194

**Comment by jgainerdewar** [comment]
Alas, we'll take a look!

**Comment by jgainerdewar** [comment]
Tests should be good now!

**Comment by mcovarr** [comment]
Thanks Janet, tests are passing here! 🎉  I wish I could say the same for the tests in `firecloud-develop`, I think those are just being flakey but very persistently so...

**Review by jgainerdewar — APPROVED** [review]
LGTM! Just to confirm my understanding - this changeset is testing only, right?  It adds tests to validate that the Nirvana image works as expected and updates the other test reference disk to be more like the one we use in Terra, but shouldn't change any behavior beyond that.

**Comment by mcovarr** [comment]
Yes this PR is tests only: adding tests for our Nirvana image and updating the existing tests to test what's actually in production (for historical reasons it was testing a config that didn't actually make it to production).

The [firecloud-develop](https://github.com/broadinstitute/firecloud-develop/pull/3194) PR is what actually would actually update Cromwell in Terra for the Nirvana reference image.

**Review by aednichols — APPROVED** [review]

**Comment by mcovarr** [comment]
Thank you for the thumbs! A friendly reminder that the related https://github.com/broadinstitute/firecloud-develop/pull/3194 needs similar thumbing to actually make this reference image available in Terra.

**Pull request merged**
