### PR TITLE
Bumped upcoming version. Added changelog entry for 1.0.0

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

**Comment by geoffjentry** [comment]
Assuming you rooted out all of the `0.` references going forward 👍

**Comment by mcovarr** [comment]
:+1: yeah I math real good

**Comment by geoffjentry** [comment]
:-1: to the 1.0.0 vs 23

**Comment by geoffjentry** [comment]
To explain, "1.0" is a very loaded term in my mind. People have already been ignoring the `0.` colloquially anyways, I'd rather just drop it and move on with life

**Comment by geoffjentry** [comment]
rescinded my thumb and the two thumbs up label until the actual number issue is resolved.

**Comment by cjllanwarne** [comment]
I agree with @geoffjentry. Going to merge as 23.

I think that's the way our versioning has been going anyway (even if we've been timidly adding 0. to the start of our version numbers). And semver is nowhere near the horizon (or even particularly wanted by the sounds of it).

**Pull request merged**
