### PR TITLE
Restore MainSpec.  Closes #1041

### LINKED ISSUE #1041: Assess/Fix/Implement Ignored Tests in MainSpec
The goal here is to look at the tests in the spec, and determine
1. does the test assess something valuable
2. if no, delete it (with an explanation in the PR)
3. if yes, either fix it up so it passes, or reimplement... whatever is more expedient

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Comment by mcovarr** [comment]
It was taking 12-14 seconds between the time the GetStatus message was received by the ServiceRegistryActor and the time it was received by the EngineMetadataServiceActor.  All sorts of other test stuff was executing in the interim, but the timeout for status queries previously defaulted to 10 seconds so that wasn't going to work.  Added an explicit 30 second dilated timeout as in many other spots.

**Comment by Horneth** [comment]
Should we also look into a way not to have the same ServiceRegistryActor for all tests ?

**Comment by mcovarr** [comment]
I'm not actually sure we do have the same ServiceRegistryActor for all tests, so we'd have to start looking into that first.  😄

**Comment by kshakir** [comment]
👍

**Comment by Horneth** [comment]
👍

**Pull request merged**
