### PR TITLE
Jes auth

### PR DESCRIPTION
**Pull request by Horneth**
Clean up JesAuthentication to work with latest FileSystem changes

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1:

**Comment by mcovarr** [comment]
any idea what's up with that test failure?

**Comment by Horneth** [comment]
Nop, it's weird I can't see any information in the Travis logs about this test, and it passes on my laptop

**Comment by scottfrazer** [comment]
:+1: barring the test failure... I looked into it briefly but I didn't figure anything out

**Pull request merged**
