### PR TITLE
Fixed bug interpreting default runtime attribute values twice. Closes #1465

### LINKED ISSUE #1465: Can no longer use docker image on local backend
- dev snapshot of cromwell pre-0.21
- local backend
- Specifying docker from options file
- Fails when running with sudo or without (same error)
- ``wdltool`` validates successfully
- Being run on google cloud VM 
- And after error occurs, cromwell stays running.   

I believe that this was working, as is, in cromwell 0.19.

I believe that it is having trouble parsing the option file.

Command:
```bash
java -Xmx4g -Dconfig.file=local_application.conf -jar \
/home/lichtens/test_eval/cromwell-0.20-028b74a-SNAPSHOT.jar run case_gatk_acnv_workflow.final.wdl \ 
/home/lichtens/eval-gatk-protected/scripts/crsp_validation/crsp_validation_gatkp_run_local_paths.json.final.json \
default_runtimes \
/home/lichtens/eval-gatk-protected/scripts/crsp_validation/crsp_validation_gatkp_run_local_paths.json.metadata.json
```

Error message:
```
[2016-09-21 17:51:25,15] [error] Expression evaluation failed due to wdl4s.WdlExpressionException: Cannot perform operation: WdlString(broadinstitute) / WdlString(gatk): WdlExpression((Subtract: lhs=(Divide: lhs=<string:1:1 identifier "YnJvYWRpbnN0aXR1dGU=">, rhs=<string:1:16 identifier "Z2F0aw==">), rhs=<string:1:21 identifier "cHJvdGVjdGVk">))
java.lang.RuntimeException: Expression evaluation failed due to wdl4s.WdlExpressionException: Cannot perform operation: WdlString(broadinstitute) / WdlString(gatk): WdlExpression((Subtract: lhs=(Divide: lhs=<string:1:1 identifier "YnJvYWRpbnN0aXR1dGU=">, rhs=<string:1:16 identifier "Z2F0aw==">), rhs=<string:1:21 identifier "cHJvdGVjdGVk">))
        at cromwell.backend.validation.RuntimeAttributesValidation$class.validateOptionalExpression(RuntimeAttributesValidation.scala:319)
        at cromwell.backend.validation.RuntimeAttributesValidation$$anon$1.validateOptionalExpression(RuntimeAttributesValidation.scala:90)
        at cromwell.backend.sfs.SharedFileSystemInitializationActor$$anonfun$runtimeAttributeValidators$1$$anonfun$apply$1.apply(SharedFileSystemInitializationActor.scala:48)
        at cromwell.backend.sfs.SharedFileSystemInitializationActor$$anonfun$runtimeAttributeValidators$1$$anonfun$apply$1.apply(SharedFileSystemInitializationActor.scala:48)
        at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$badRuntimeAttrsForTask$1$2.apply(BackendWorkflowInitializationActor.scala:141)
        at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$badRuntimeAttrsForTask$1$2.apply(BackendWorkflowInitializationActor.scala:139)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
....snip....
```

default_runtime:
```
{
  "default_runtime_attributes": {
      "docker": "broadinstitute/gatk-protected:24e6bdc0c058eaa9abe63e1987418d0c144fef8e",
          "zones": "us-central1-a us-central1-b",
          "disks": "local-disk 200 SSD",
          "memory": "6G"
            }
}
```

Relevant snippet from local_application.conf:
```
....
    Local {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        run-in-background = true
        runtime-attributes = "String? docker"
        submit = "/bin/bash ${script}"
        submit-docker = "docker run --rm -v ${cwd}:${docker_cwd} -i ${docker} /bin/bash < ${script}"

        // Root directory where Cromwell writes job results.  This directory must be
        // visible and writeable by the Cromwell process as well as the jobs that Cromwell
        // launches.
        root: "cromwell-executions"

        filesystems {
          gcs {
                // A reference to a potentially different auth for manipulating files via engine functions.
                auth = "application-default"
          }

          local {
            // Cromwell makes a link to your input files within <root>/<workflow UUID>/workflow-inputs
            // The following are strategies used to make those links.  They are ordered.  If one fails
            // The next one is tried:
            //
            // hard-link: attempt to create a hard-link to the file
            // copy: copy the file
            // soft-link: create a symbolic link to the file
            //
            // NOTE: soft-link will be skipped for Docker jobs
            localization: [
              "hard-link", "soft-link", "copy"
            ]
          }
        }
      }
    }
......
```

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

**Comment by Horneth** [comment]
I imagine that's the point, but just to make sure this won't allow for expressions in workflow option default runtime attributes anymore (maybe that wasn't even a wanted feature in the first place).

**Comment by cjllanwarne** [comment]
@Horneth Actually this doesn't change any behaviour except one: the defaults are **already** values, this just stops the being converted back into Expressions (badly) and then re-evaluated into Values again

**Comment by mcovarr** [comment]
nice!  :+1:

**Comment by Horneth** [comment]
👍

**Pull request merged**
