### PR TITLE
Use correct conf key name for refresh token creds

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by kshakir** [comment]
I'd like to see an optional test, similar to the other `GoogleCredentialFactorySpec` tests.

**Comment by cjllanwarne** [comment]
Looks correct to me - :+1: when Khalid's happy

**Comment by kshakir** [comment]
I'm willing to defer on testing, under our current mantra "we'll get to full CI eventually". Will let @Horneth decide for now. LGTM

**Comment by Horneth** [comment]
What about simply a unit test that verifies that it does (resp. doesn't) parse a correct (resp. wrong) conf file (wrt Google configuration) ?

**Comment by cjllanwarne** [comment]
I like the tests - should make it harder to accidentally rebase/merge config incorrectly in the future. :+1:

**Pull request merged**
