### PR TITLE
Minor fixes to Cromwell server repo config [BT-243]

### PR DESCRIPTION
**Pull request by mcovarr**
tyvm for the super useful repo config! I found a couple of minor issues while working on BT-226 as documented in BT-243.

Before: 
Screen Shot 2021-04-25 at 11 11 12 AM

After:
Screen Shot 2021-04-25 at 11 15 01 AM

### CODE REVIEW

**Review by kshakir — APPROVED** [review]
LGTM in general, minus the `prsalt.txt`. All ToL:

- `git commit --amend --date=now --reuse-message=HEAD` plus a force push is also a way to kick off an otherwise stuck CI, and then you don't have to remove any files later.

- Because of the change from `src` to `target` one will have to run `sbt copyCiResources` or `sbt renderCiResources` at some point before running this configuration. I'm not sure if there's a way to invoke that automagically in these `runConfigurations`?

- I haven't tried this PR out myself so I'm not sure how the JRE selection works, but `$USER_HOME$/.sdkman/candidates/java/current` looks like it could differ between folks machines. Maybe `$USER_HOME$/.sdkman/candidates/java/11.0.10.hs-adpt` would be more static, and could be updated in the future at the same time as the [`.sdkmanrc`](https://github.com/broadinstitute/cromwell/blob/61/.sdkmanrc#L3)

**Comment by mcovarr** [comment]
- Removed `prsalt.txt`.
- Added an sbt run configuration for `renderCiResources` and set the 'Cromwell server' configuration to invoke it before launching the server.
- The "JDK of 'cromwell' module" seemed like the least problematic choice of JDK; specifying particular patch levels and builds of JDK 11 seemed like it might not work out well as updates become available...

**Review by kshakir — APPROVED** [review]
Haven't tested these runConfigurations myself (I run with in-memory databases), so gonna give this a LGTM. Also it look like as of 2466208 there are commits from BT-226 leaking in to this PR.

**Comment by mcovarr** [comment]
oops, BT-226 leakage should be resolved now

**Review by breilly2 — APPROVED** [review]

**Pull request merged**
